label var factid_9_value "Safety of care national comparison"  
label var factid_3_value "Efficient use of medical imaging national comparison"  
label var factid_6_value "Mortality national comparison"  
label var factid_7_value "Patient experience national comparison"  
label var factid_1_value "Accreditation"  
label var factid_10_value "Timeliness of care national comparison"  
label var factid_4_value "Hospital overall rating"  
label var factid_5_value "Meets criteria for meaningful use of EHRs"  
label var factid_2_value "Effectiveness of care national comparison"  
label var factid_8_value "Readmission national comparison"  
label var acs_registry_response "Multispecialty surgical registry"  
label var op_12_response "Able to receive lab results electronically"  
label var op_17_response "Able to track patients’ lab results, tests, and referrals electronically between"  
label var op_25_response "Safe surgery checklist use (outpatient)"  
label var sm_part_card_response "Cardiac surgery registry"  
label var sm_part_gen_surg_response "General Surgery Registry"  
label var sm_part_nurse_response "Nursing care registry"  
label var sm_part_stroke_response "Stroke care registry"  
label var sm_ss_check_response "Safe surgery checklist use (inpatient)"  
label var readm_30_ami_numberofdischarges "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_copd_numberofdischarges "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_numberofdischarges "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_numberofdischa "Rate of readmission after hip/knee replacement"  
label var readm_30_pn_numberofdischarges "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_ami_excessreadmissionra "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_copd_excessreadmissionr "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_excessreadmissionrat "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_excessreadmiss "Rate of readmission after hip/knee replacement"  
label var readm_30_pn_excessreadmissionrat "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_ami_predictedreadmissio "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_copd_predictedreadmissi "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_predictedreadmission "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_predictedreadm "Rate of readmission after hip/knee replacement"  
label var readm_30_pn_predictedreadmission "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_ami_expectedreadmission "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_copd_expectedreadmissio "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_expectedreadmissionr "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_expectedreadmi "Rate of readmission after hip/knee replacement"  
label var readm_30_pn_expectedreadmissionr "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_ami_numberofreadmission "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_copd_numberofreadmissio "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_numberofreadmissions "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_numberofreadmi "Rate of readmission after hip/knee replacement"  
label var readm_30_pn_numberofreadmissions "Pneumonia (PN) 30-Day Readmission Rate"  
label var op_10_score "Abdomen CT Use of Contrast Material"  
label var op_11_score "Thorax CT Use of Contrast Material"  
label var op_13_score "Outpatients who got cardiac imaging stress tests before low-risk outpatient surg"  
label var op_14_score "Outpatients with brain CT scans who got a sinus CT scan at the same time"  
label var op_8_score "MRI Lumbar Spine for Low Back Pain"  
label var op_9_score "Mammography Follow-up Rates"  
label var op_10_sample "Abdomen CT Use of Contrast Material"  
label var op_11_sample "Thorax CT Use of Contrast Material"  
label var op_13_sample "Outpatients who got cardiac imaging stress tests before low-risk outpatient surg"  
label var op_14_sample "Outpatients with brain CT scans who got a sinus CT scan at the same time"  
label var op_8_sample "MRI Lumbar Spine for Low Back Pain"  
label var op_9_sample "Mammography Follow-up Rates"  
label var mspb_1_score "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"  
label var paym_30_ami_payment "Payment for heart attack patients"  
label var paym_30_hf_payment "Payment for heart failure patients"  
label var paym_30_pn_payment "Payment for pneumonia patients"  
label var paym_30_ami_lowerestimate "Payment for heart attack patients"  
label var paym_30_hf_lowerestimate "Payment for heart failure patients"  
label var paym_30_pn_lowerestimate "Payment for pneumonia patients"  
label var paym_30_ami_higherestimate "Payment for heart attack patients"  
label var paym_30_hf_higherestimate "Payment for heart failure patients"  
label var paym_30_pn_higherestimate "Payment for pneumonia patients"  
label var paym_30_ami_denominator "Payment for heart attack patients"  
label var paym_30_hf_denominator "Payment for heart failure patients"  
label var paym_30_pn_denominator "Payment for pneumonia patients"  
label var paym_30_ami_nationalcomparisonca "Payment for heart attack patients"  
label var paym_30_hf_nationalcomparisoncat "Payment for heart failure patients"  
label var paym_30_pn_nationalcomparisoncat "Payment for pneumonia patients"  
label var hai_1_standardizedinfectionratio "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_standardizedinfectionrati "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_standardizedinfectionratio "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_standardizedinfectionrati "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_standardizedinfectionratio "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_standardizedinfectionratio "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_standardizedinfectionratio "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_standardizedinfectionratio "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var combinedssimeasurescore_perfo ""  
label var haiconditionprocedurescore_pe ""  
label var hai_1_performancerate "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_2_performancerate "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_3_performancerate "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_performancerate "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hfconditionprocedurescore_per ""  
label var hf_1_performancerate "Discharge instructions"  
label var imm_2_performancerate "Immunization for influenza"  
label var mort_30_ami_performancerate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_hf_performancerate "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_performancerate "Pneumonia (PN) 30-Day Mortality Rate"  
label var mspb_1_performancerate "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"  
label var pnconditionprocedurescore_per ""  
label var pn_3b_performancerate "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_6_performancerate "Initial antibiotic selection for CAP in immunocompetent patient"  
label var preventiveconditionprocedures ""  
label var psi_90_safety_performancerate "Serious complications"  
label var scipconditionprocedurescore_p ""  
label var scip_card_2_performancerate "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_performancerate "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_2_performancerate "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_performancerate "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_performancerate "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_9_performancerate "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_performancerate "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_performancerate "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var pch_1_numerator ""  
label var pch_2_numerator ""  
label var pch_1_denominator ""  
label var pch_2_denominator ""  
label var tpsid_9_measurescore "Weighted Patient Experience of Care Domain Score"  
label var tpsid_3_measurescore "Unweighted Normalized Efficiency Domain Score"  
label var tpsid_6_measurescore "Weighted Clinical Process of Care Domain Score"  
label var tpsid_7_measurescore "Weighted Efficiency Domain Score"  
label var tpsid_1_measurescore "Total Performance Score"  
label var tpsid_4_measurescore "Unweighted Normalized Outcome Domain Score"  
label var tpsid_5_measurescore "Unweighted Patient Experience of Care Domain Score"  
label var tpsid_2_measurescore "Unweighted Normalized Clinical Process of Care Domain Score"  
label var tpsid_8_measurescore "Weighted Outcome Domain Score"  
label var mid_60_ptid_7_procedurevolume "OTHER"  
label var mid_60_ptid_1_procedurevolume "CARDIOVASCULAR"  
label var mid_60_ptid_4_procedurevolume "GENITOURINARY"  
label var mid_60_ptid_2_procedurevolume "EYE"  
label var mid_60_ptid_5_procedurevolume "MUSCULOSKELETAL"  
label var mid_60_ptid_8_procedurevolume "RESPIRATORY"  
label var mid_60_ptid_9_procedurevolume "SKIN"  
label var mid_60_ptid_3_procedurevolume "GASTROINTESTINAL"  
label var mid_60_ptid_6_procedurevolume "NERVOUS SYSTEM"  
label var mid_3_achievementpoints "COMMUNICATION WITH DOCTORS"  
label var mid_6_achievementpoints "OVERALL RATING OF HOSPITAL"  
label var mid_7_achievementpoints "PAIN MANAGEMENT"  
label var mid_1_achievementpoints "CLEANLINESS AND QUIETNESS OF HOSPITAL ENVIRONMENT"  
label var mid_4_achievementpoints "COMMUNICATION WITH NURSES"  
label var mid_5_achievementpoints "DISCHARGE INFORMATION"  
label var mid_2_achievementpoints "COMMUNICATION ABOUT MEDICINES"  
label var mid_8_achievementpoints "RESPONSIVENESS OF HOSPITAL STAFF"  
label var mid_3_dimensionscore "COMMUNICATION WITH DOCTORS"  
label var mid_6_dimensionscore "OVERALL RATING OF HOSPITAL"  
label var mid_7_dimensionscore "PAIN MANAGEMENT"  
label var mid_1_dimensionscore "CLEANLINESS AND QUIETNESS OF HOSPITAL ENVIRONMENT"  
label var mid_4_dimensionscore "COMMUNICATION WITH NURSES"  
label var mid_5_dimensionscore "DISCHARGE INFORMATION"  
label var mid_2_dimensionscore "COMMUNICATION ABOUT MEDICINES"  
label var mid_8_dimensionscore "RESPONSIVENESS OF HOSPITAL STAFF"  
label var mid_3_improvementpoints "COMMUNICATION WITH DOCTORS"  
label var mid_6_improvementpoints "OVERALL RATING OF HOSPITAL"  
label var mid_7_improvementpoints "PAIN MANAGEMENT"  
label var mid_1_improvementpoints "CLEANLINESS AND QUIETNESS OF HOSPITAL ENVIRONMENT"  
label var mid_4_improvementpoints "COMMUNICATION WITH NURSES"  
label var mid_5_improvementpoints "DISCHARGE INFORMATION"  
label var mid_2_improvementpoints "COMMUNICATION ABOUT MEDICINES"  
label var mid_8_improvementpoints "RESPONSIVENESS OF HOSPITAL STAFF"  
label var combinedssimeasurescore_achie ""  
label var haiconditionprocedurescore_ac ""  
label var hai_1_achievementpoints "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_2_achievementpoints "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_3_achievementpoints "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_achievementpoints "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hfconditionprocedurescore_ach ""  
label var hf_1_achievementpoints "Discharge instructions"  
label var imm_2_achievementpoints "Immunization for influenza"  
label var mort_30_ami_achievementpoints "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_hf_achievementpoints "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_achievementpoints "Pneumonia (PN) 30-Day Mortality Rate"  
label var mspb_1_achievementpoints "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"  
label var pnconditionprocedurescore_ach ""  
label var pn_3b_achievementpoints "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_6_achievementpoints "Initial antibiotic selection for CAP in immunocompetent patient"  
label var preventiveconditionprocedures ""  
label var psi_90_safety_achievementpoints "Serious complications"  
label var scipconditionprocedurescore_a ""  
label var scip_card_2_achievementpoints "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_achievementpoints "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_2_achievementpoints "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_achievementpoints "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_achievementpoints "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_9_achievementpoints "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_achievementpoints "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_achievementpoints "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var combinedssimeasurescore_impro ""  
label var haiconditionprocedurescore_im ""  
label var hai_1_improvementpoints "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_2_improvementpoints "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_3_improvementpoints "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_improvementpoints "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hfconditionprocedurescore_imp ""  
label var hf_1_improvementpoints "Discharge instructions"  
label var imm_2_improvementpoints "Immunization for influenza"  
label var mort_30_ami_improvementpoints "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_hf_improvementpoints "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_improvementpoints "Pneumonia (PN) 30-Day Mortality Rate"  
label var mspb_1_improvementpoints "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"  
label var pnconditionprocedurescore_imp ""  
label var pn_3b_improvementpoints "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_6_improvementpoints "Initial antibiotic selection for CAP in immunocompetent patient"  
label var preventiveconditionprocedures ""  
label var psi_90_safety_improvementpoints "Serious complications"  
label var scipconditionprocedurescore_i ""  
label var scip_card_2_improvementpoints "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_improvementpoints "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_2_improvementpoints "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_improvementpoints "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_improvementpoints "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_9_improvementpoints "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_improvementpoints "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_improvementpoints "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var combinedssimeasurescore_measu ""  
label var haiconditionprocedurescore_me ""  
label var hai_1_measurescore "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_2_measurescore "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_3_measurescore "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_measurescore "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hfconditionprocedurescore_mea ""  
label var hf_1_measurescore "Discharge instructions"  
label var imm_2_measurescore "Immunization for influenza"  
label var mort_30_ami_measurescore "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_hf_measurescore "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_measurescore "Pneumonia (PN) 30-Day Mortality Rate"  
label var mspb_1_measurescore "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"  
label var pnconditionprocedurescore_mea ""  
label var pn_3b_measurescore "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_6_measurescore "Initial antibiotic selection for CAP in immunocompetent patient"  
label var preventiveconditionprocedures ""  
label var psi_90_safety_measurescore "Serious complications"  
label var scipconditionprocedurescore_m ""  
label var scip_card_2_measurescore "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_measurescore "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_2_measurescore "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_measurescore "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_measurescore "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_9_measurescore "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_measurescore "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_measurescore "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var ami_1_score "Heart Attack Patients Given Aspirin at Arrival"  
label var ami_10_score "Statin at Discharge"  
label var ami_2_score "Aspirin prescribed at discharge"  
label var ami_3_score "Heart Attack Patients Given ACE Inhibitor or ARB for Left Ventricular Systolic D"  
label var ami_4_score "Heart Attack Patients Given Smoking Cessation Advice/Counseling"  
label var ami_5_score "Heart Attack Patients Given Beta Blocker at Discharge"  
label var ami_7a_score "Fibrinolytic Therapy Received Within 30 Minutes Of Hospital Arrival"  
label var ami_8a_score "Primary PCI Received Within 90 Minutes of Hospital Arrival"  
label var cac_1_score "Relievers for Inpatient Asthma"  
label var cac_2_score "Systemic Corticosteroids for Inpatient Asthma"  
label var cac_3_score "Home Management Plan of Care Document"  
label var ed_1b_score "ED1"  
label var ed_2b_score "ED2"  
label var edv_score "Emergency department volume"  
label var hf_1_score "Discharge instructions"  
label var hf_2_score "Evaluation of LVS Function"  
label var hf_3_score "ACEI or ARB for LVSD"  
label var hf_4_score "Heart Failure Patients Given Smoking Cessation Advice/Counseling"  
label var imm_1a_score ""  
label var imm_2_score "Immunization for influenza"  
label var imm_3_fac_adhpct_score "Healthcare workers given influenza vaccination"  
label var imm_3_op_27_fac_adhpct_score "Healthcare workers given influenza vaccination"  
label var op_1_score "Median Time to Fibrinolysis"  
label var op_18b_score "OP 18"  
label var op_2_score "Fibrinolytic Therapy Received Within 30 Minutes of ED Arrival"  
label var op_20_score "Door to diagnostic eval"  
label var op_21_score "Median time to pain med"  
label var op_22_score "Left before being seen"  
label var op_23_score "Head CT results"  
label var op_29_score "Endoscopy/Polyp Surveillance: Appropriate Follow-Up Interval for Normal Colonosc"  
label var op_30_score "Endoscopy/Polyp Surveillance: Colonoscopy Interval for Patients with a History o"  
label var op_3b_score "Median Time to Transfer to Another Facility for Acute Coronary Intervention"  
label var op_4_score "Aspirin at Arrival"  
label var op_5_score "Median Time to ECG"  
label var op_6_score "Prophylactic Antibiotic Initiated Within One Hour Prior to Surgical Incision"  
label var op_7_score "Prophylactic Antibiotic Selection for Surgical Patients"  
label var pc_01_score "Percent of newborns whose deliveries were scheduled early (1-3 weeks early), whe"  
label var pn_1_score "Pneumonia Patients Given Oxygenation Assessment"  
label var pn_2_score "Pneumonia Patients Assessed and Given Pneumococcal Vaccination"  
label var pn_3b_score "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_4_score "Pneumonia Patients Given Smoking Cessation Advice/Counseling"  
label var pn_5c_score "Pneumonia Patients Given Initial Antibiotic(s) within 6 Hours After Arrival"  
label var pn_6_score "Initial antibiotic selection for CAP in immunocompetent patient"  
label var pn_7_score "Pneumonia Patients Assessed and Given Influenza Vaccination"  
label var scip_card_2_score "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_score "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_10_score "Surgery Patients with Perioperative Temperature Management"  
label var scip_inf_2_score "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_score "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_score "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_6_score "Surgery patients needing hair removed from the surgical area before surgery, who"  
label var scip_inf_9_score "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_score "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_score "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var stk_1_score "Venous Thromboembolism (VTE) Prophylaxis"  
label var stk_10_score "Assessed for Rehabilitation"  
label var stk_2_score "Discharged on Antithrombotic Therapy"  
label var stk_3_score "Anticoagulation Therapy for Atrial Fibrillation/Flutter"  
label var stk_4_score "Thrombolytic Therapy"  
label var stk_5_score "Antithrombotic Therapy by End of Hospital Day 2"  
label var stk_6_score "Discharged on Statin Medication"  
label var stk_8_score "Stroke Education"  
label var vte_1_score "Venous thromboembolism prophylaxis"  
label var vte_2_score "ICU venous thromboembolism prophylaxis"  
label var vte_3_score "Anticoagulation overlap therapy"  
label var vte_4_score "Unfractionated heparin with dosages/platelet count monitoring"  
label var vte_5_score "Warfarin therapy discharge instructions"  
label var vte_6_score "Hospital acquired potentially preventable venous thromboembolism"  
label var hai_1_confidenceintervallower "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_confidenceintervallower "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_confidenceintervallower "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_confidenceintervallower "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_confidenceintervallower "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_confidenceintervallower "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_confidenceintervallower "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_confidenceintervallower "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var hai_1_confidenceintervalhigher "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_confidenceintervalhigher "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_confidenceintervalhigher "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_confidenceintervalhigher "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_confidenceintervalhigher "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_confidenceintervalhigher "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_confidenceintervalhigher "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_confidenceintervalhigher "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var ami_1_sample "Heart Attack Patients Given Aspirin at Arrival"  
label var ami_10_sample "Statin at Discharge"  
label var ami_2_sample "Aspirin prescribed at discharge"  
label var ami_3_sample "Heart Attack Patients Given ACE Inhibitor or ARB for Left Ventricular Systolic D"  
label var ami_4_sample "Heart Attack Patients Given Smoking Cessation Advice/Counseling"  
label var ami_5_sample "Heart Attack Patients Given Beta Blocker at Discharge"  
label var ami_7a_sample "Fibrinolytic Therapy Received Within 30 Minutes Of Hospital Arrival"  
label var ami_8a_sample "Primary PCI Received Within 90 Minutes of Hospital Arrival"  
label var cac_1_sample "Relievers for Inpatient Asthma"  
label var cac_2_sample "Systemic Corticosteroids for Inpatient Asthma"  
label var cac_3_sample "Home Management Plan of Care Document"  
label var ed_1b_sample "ED1"  
label var ed_2b_sample "ED2"  
label var edv_sample "Emergency department volume"  
label var hf_1_sample "Discharge instructions"  
label var hf_2_sample "Evaluation of LVS Function"  
label var hf_3_sample "ACEI or ARB for LVSD"  
label var hf_4_sample "Heart Failure Patients Given Smoking Cessation Advice/Counseling"  
label var imm_1a_sample ""  
label var imm_2_sample "Immunization for influenza"  
label var imm_3_fac_adhpct_sample "Healthcare workers given influenza vaccination"  
label var imm_3_op_27_fac_adhpct_sample "Healthcare workers given influenza vaccination"  
label var op_1_sample "Median Time to Fibrinolysis"  
label var op_18b_sample "OP 18"  
label var op_2_sample "Fibrinolytic Therapy Received Within 30 Minutes of ED Arrival"  
label var op_20_sample "Door to diagnostic eval"  
label var op_21_sample "Median time to pain med"  
label var op_22_sample "Left before being seen"  
label var op_23_sample "Head CT results"  
label var op_29_sample "Endoscopy/Polyp Surveillance: Appropriate Follow-Up Interval for Normal Colonosc"  
label var op_30_sample "Endoscopy/Polyp Surveillance: Colonoscopy Interval for Patients with a History o"  
label var op_3b_sample "Median Time to Transfer to Another Facility for Acute Coronary Intervention"  
label var op_4_sample "Aspirin at Arrival"  
label var op_5_sample "Median Time to ECG"  
label var op_6_sample "Prophylactic Antibiotic Initiated Within One Hour Prior to Surgical Incision"  
label var op_7_sample "Prophylactic Antibiotic Selection for Surgical Patients"  
label var pc_01_sample "Percent of newborns whose deliveries were scheduled early (1-3 weeks early), whe"  
label var pn_1_sample "Pneumonia Patients Given Oxygenation Assessment"  
label var pn_2_sample "Pneumonia Patients Assessed and Given Pneumococcal Vaccination"  
label var pn_3b_sample "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"  
label var pn_4_sample "Pneumonia Patients Given Smoking Cessation Advice/Counseling"  
label var pn_5c_sample "Pneumonia Patients Given Initial Antibiotic(s) within 6 Hours After Arrival"  
label var pn_6_sample "Initial antibiotic selection for CAP in immunocompetent patient"  
label var pn_7_sample "Pneumonia Patients Assessed and Given Influenza Vaccination"  
label var scip_card_2_sample "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "  
label var scip_inf_1_sample "Prophylactic antibiotic received within 1 hour prior to surgical incision"  
label var scip_inf_10_sample "Surgery Patients with Perioperative Temperature Management"  
label var scip_inf_2_sample "Prophylactic Antibiotic Selection for Surgical Patients"  
label var scip_inf_3_sample "Prophylactic antibiotics discontinued within 24 hours after surgery end time"  
label var scip_inf_4_sample "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"  
label var scip_inf_6_sample "Surgery patients needing hair removed from the surgical area before surgery, who"  
label var scip_inf_9_sample "Postoperative Urinary Catheter Removal"  
label var scip_vte_1_sample "Surgery patients whose doctors ordered treatments to prevent blood clots after c"  
label var scip_vte_2_sample "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"  
label var stk_1_sample "Venous Thromboembolism (VTE) Prophylaxis"  
label var stk_10_sample "Assessed for Rehabilitation"  
label var stk_2_sample "Discharged on Antithrombotic Therapy"  
label var stk_3_sample "Anticoagulation Therapy for Atrial Fibrillation/Flutter"  
label var stk_4_sample "Thrombolytic Therapy"  
label var stk_5_sample "Antithrombotic Therapy by End of Hospital Day 2"  
label var stk_6_sample "Discharged on Statin Medication"  
label var stk_8_sample "Stroke Education"  
label var vte_1_sample "Venous thromboembolism prophylaxis"  
label var vte_2_sample "ICU venous thromboembolism prophylaxis"  
label var vte_3_sample "Anticoagulation overlap therapy"  
label var vte_4_sample "Unfractionated heparin with dosages/platelet count monitoring"  
label var vte_5_sample "Warfarin therapy discharge instructions"  
label var vte_6_sample "Hospital acquired potentially preventable venous thromboembolism"  
label var hai_1_numberofdaysorpatients "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_numberofdaysorpatients "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_numberofdaysorpatients "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_numberofdaysorpatients "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_numberofdaysorpatients "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_numberofdaysorpatients "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_numberofdaysorpatients "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_numberofdaysorpatients "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var drgid_355_averagepayment "Hernia procedures except inguinal and femoral w/o CC/MCC"  
label var drgid_192_averagepayment "Chronic obstructive pulmonary disease w/o CC/MCC"  
label var drgid_418_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w CC"  
label var drgid_221_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w/o CC/MCC"  
label var drgid_470_averagepayment "Major joint replacement or reattachment of lower extremity w/o MCC"  
label var drgid_673_averagepayment "Other kidney and urinary tract procedures w MCC"  
label var drgid_507_averagepayment "Major shoulder or elbow joint procedures w CC/MCC"  
label var drgid_656_averagepayment "Kidney and ureter procedures for neoplasm w MCC"  
label var drgid_244_averagepayment "Permanent cardiac pacemaker implant w/o CC/MCC"  
label var drgid_473_averagepayment "Cervical spinal fusion w/o CC/MCC"  
label var drgid_281_averagepayment "Acute myocardial infarction, discharged alive w CC"  
label var comp_hip_knee_score "Rate of complications for hip/knee replacement patients"  
label var iqi_11_aaa_score ""  
label var iqi_19_hip_fx_score ""  
label var iqi_91_conds_score ""  
label var mort_30_ami_score "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_cabg_score "Death rate for CABG"  
label var mort_30_copd_score "Death rate for chronic obstructive pulmonary disease (COPD) patients"  
label var mort_30_hf_score "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_score "Pneumonia (PN) 30-Day Mortality Rate"  
label var mort_30_stk_score "Death rate for stroke patients"  
label var psi_11_postop_respfail_score ""  
label var psi_12_postop_pulmemb_dvt_score "Serious blood clots after surgery"  
label var psi_13_post_sepsis_score "Blood stream infection after surgery"  
label var psi_14_postop_dehis_score "A wound that splits open  after surgery on the abdomen or pelvis"  
label var psi_15_acc_lac_score "Accidental cuts and tears from medical treatment"  
label var psi_3_ulcer_score "Pressure sores"  
label var psi_4_surg_comp_score "Deaths among Patients with Serious Treatable Complications after Surgery"  
label var psi_6_iat_ptx_score "Collapsed lung due to medical treatment"  
label var psi_7_cvcbi_score "Infections from a large venous catheter"  
label var psi_8_post_hip_score "Broken hip from a fall after surgery"  
label var psi_90_safety_score "Serious complications"  
label var readm_30_ami_score "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_cabg_score "Rate of readmission for CABG"  
label var readm_30_copd_score "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_score "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_score "Rate of readmission after hip/knee replacement"  
label var readm_30_hosp_wide_score "Rate of readmission after discharge from hospital (hospital-wide)"  
label var readm_30_pn_score "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_stk_score "Rate of readmission for stroke patients"  
label var hai_1_numerator "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_numerator "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_numerator "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_numerator "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_numerator "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_numerator "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_numerator "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_numerator "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var hai_1_nationalcomparisoncategory "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"  
label var hai_1a_nationalcomparisoncategor "Central line-associated blood stream infections (CLABSI) in ICUs only"  
label var hai_2_nationalcomparisoncategory "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"  
label var hai_2a_nationalcomparisoncategor "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"  
label var hai_3_nationalcomparisoncategory "Surgical Site Infection from colon surgery (SSI: Colon)"  
label var hai_4_nationalcomparisoncategory "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"  
label var hai_5_nationalcomparisoncategory "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"  
label var hai_6_nationalcomparisoncategory "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"  
label var drgid_220_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w CC"  
label var drgid_469_averagepayment "Major joint replacement or reattachment of lower extremity w MCC"  
label var drgid_515_averagepayment "Other musculoskelet sys and conn tiss O.R. proc w MCC"  
label var drgid_243_averagepayment "Permanent cardiac pacemaker implant w CC"  
label var drgid_355_denominator "Hernia procedures except inguinal and femoral w/o CC/MCC"  
label var drgid_192_denominator "Chronic obstructive pulmonary disease w/o CC/MCC"  
label var drgid_418_denominator "Laparoscopic cholecystectomy w/o c.d.e. w CC"  
label var drgid_221_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w/o CC/MCC"  
label var drgid_470_denominator "Major joint replacement or reattachment of lower extremity w/o MCC"  
label var drgid_673_denominator "Other kidney and urinary tract procedures w MCC"  
label var drgid_507_denominator "Major shoulder or elbow joint procedures w CC/MCC"  
label var drgid_656_denominator "Kidney and ureter procedures for neoplasm w MCC"  
label var drgid_244_denominator "Permanent cardiac pacemaker implant w/o CC/MCC"  
label var drgid_473_denominator "Cervical spinal fusion w/o CC/MCC"  
label var drgid_281_denominator "Acute myocardial infarction, discharged alive w CC"  
label var drgid_235_denominator "Coronary bypass w/o cardiac cath w MCC"  
label var drgid_659_denominator "Kidney and ureter procedures for non-neoplasm w MCC"  
label var drgid_467_denominator "Revision of hip or knee replacement w CC"  
label var drgid_713_denominator "Transurethral prostatectomy w CC/MCC"  
label var drgid_461_denominator "Bilateral or multiple major joint procs of lower extremity w MCC"  
label var drgid_292_denominator "Heart failure and shock w CC"  
label var drgid_490_denominator "Back and neck proc exc spinal fusion w CC/MCC or disc device/neurostim"  
label var drgid_190_denominator "Chronic obstructive pulmonary disease w MCC"  
label var drgid_353_denominator "Hernia procedures except inguinal and femoral w MCC"  
label var drgid_330_denominator "Major small and large bowel procedures w CC"  
label var drgid_236_denominator "Coronary bypass w/o cardiac cath w/o MCC"  
label var drgid_313_denominator "Chest Pain"  
label var drgid_668_denominator "Transurethral procedures w MCC"  
label var drgid_468_denominator "Revision of hip or knee replacement w/o CC/MCC"  
label var drgid_714_denominator "Transurethral prostatectomy w/o CC/MCC"  
label var drgid_748_denominator "Female reproductive system reconstructive procedures"  
label var drgid_462_denominator "Bilateral or multiple major joint procs of lower extremity w/o MCC"  
label var drgid_38_denominator "Extracranial procedures w CC"  
label var drgid_193_denominator "Simple pneumonia and pleurisy w MCC"  
label var drgid_293_denominator "Heart failure and shock w/o CC/MCC"  
label var drgid_479_denominator "Biopsies of musculoskeletal system and connective tissue w/o CC/MCC"  
label var drgid_224_denominator "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w MCC"  
label var comp_hip_knee_lowerestimate "Rate of complications for hip/knee replacement patients"  
label var iqi_11_aaa_lowerestimate ""  
label var iqi_19_hip_fx_lowerestimate ""  
label var iqi_91_conds_lowerestimate ""  
label var mort_30_ami_lowerestimate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_cabg_lowerestimate "Death rate for CABG"  
label var mort_30_copd_lowerestimate "Death rate for chronic obstructive pulmonary disease (COPD) patients"  
label var mort_30_hf_lowerestimate "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_lowerestimate "Pneumonia (PN) 30-Day Mortality Rate"  
label var mort_30_stk_lowerestimate "Death rate for stroke patients"  
label var psi_11_postop_respfail_loweresti ""  
label var psi_12_postop_pulmemb_dvt_lowere "Serious blood clots after surgery"  
label var psi_13_post_sepsis_lowerestimate "Blood stream infection after surgery"  
label var psi_14_postop_dehis_lowerestimat "A wound that splits open  after surgery on the abdomen or pelvis"  
label var psi_15_acc_lac_lowerestimate "Accidental cuts and tears from medical treatment"  
label var psi_3_ulcer_lowerestimate "Pressure sores"  
label var psi_4_surg_comp_lowerestimate "Deaths among Patients with Serious Treatable Complications after Surgery"  
label var psi_6_iat_ptx_lowerestimate "Collapsed lung due to medical treatment"  
label var psi_7_cvcbi_lowerestimate "Infections from a large venous catheter"  
label var psi_8_post_hip_lowerestimate "Broken hip from a fall after surgery"  
label var psi_90_safety_lowerestimate "Serious complications"  
label var readm_30_ami_lowerestimate "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_cabg_lowerestimate "Rate of readmission for CABG"  
label var readm_30_copd_lowerestimate "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_lowerestimate "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_lowerestimate "Rate of readmission after hip/knee replacement"  
label var readm_30_hosp_wide_lowerestimate "Rate of readmission after discharge from hospital (hospital-wide)"  
label var readm_30_pn_lowerestimate "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_stk_lowerestimate "Rate of readmission for stroke patients"  
label var drgid_235_averagepayment "Coronary bypass w/o cardiac cath w MCC"  
label var drgid_659_averagepayment "Kidney and ureter procedures for non-neoplasm w MCC"  
label var drgid_467_averagepayment "Revision of hip or knee replacement w CC"  
label var drgid_713_averagepayment "Transurethral prostatectomy w CC/MCC"  
label var drgid_461_averagepayment "Bilateral or multiple major joint procs of lower extremity w MCC"  
label var drgid_292_averagepayment "Heart failure and shock w CC"  
label var drgid_490_averagepayment "Back and neck proc exc spinal fusion w CC/MCC or disc device/neurostim"  
label var drgid_190_averagepayment "Chronic obstructive pulmonary disease w MCC"  
label var drgid_353_averagepayment "Hernia procedures except inguinal and femoral w MCC"  
label var drgid_330_averagepayment "Major small and large bowel procedures w CC"  
label var drgid_236_averagepayment "Coronary bypass w/o cardiac cath w/o MCC"  
label var drgid_313_averagepayment "Chest Pain"  
label var drgid_668_averagepayment "Transurethral procedures w MCC"  
label var drgid_468_averagepayment "Revision of hip or knee replacement w/o CC/MCC"  
label var drgid_714_averagepayment "Transurethral prostatectomy w/o CC/MCC"  
label var drgid_748_averagepayment "Female reproductive system reconstructive procedures"  
label var drgid_462_averagepayment "Bilateral or multiple major joint procs of lower extremity w/o MCC"  
label var drgid_38_averagepayment "Extracranial procedures w CC"  
label var drgid_193_averagepayment "Simple pneumonia and pleurisy w MCC"  
label var drgid_293_averagepayment "Heart failure and shock w/o CC/MCC"  
label var drgid_479_averagepayment "Biopsies of musculoskeletal system and connective tissue w/o CC/MCC"  
label var drgid_224_averagepayment "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w MCC"  
label var drgid_419_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w/o CC/MCC"  
label var drgid_227_averagepayment "Cardiac defibrillator implant w/o cardiac cath w/o MCC"  
label var drgid_459_averagepayment "Spinal fusion except cervical w MCC"  
label var drgid_674_averagepayment "Other kidney and urinary tract procedures w CC"  
label var drgid_508_averagepayment "Major shoulder or elbow joint procedures w/o CC/MCC"  
label var drgid_247_averagepayment "Perc cardiovasc proc w drug-eluting stent w/o MCC"  
label var drgid_282_averagepayment "Acute myocardial infarction, discharged alive w/o CC/MCC"  
label var drgid_219_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w MCC"  
label var drgid_328_averagepayment "Stomach, esophageal duodenal proc w/o CC/MCC"  
label var drgid_460_averagepayment "Spinal fusion except cervical w/o MCC"  
label var drgid_291_averagepayment "Heart failure and shock w MCC"  
label var drgid_491_averagepayment "Back and neck proc exc spinal fusion w/o CC/MCC"  
label var drgid_191_averagepayment "Chronic obstructive pulmonary disease w CC"  
label var drgid_354_averagepayment "Hernia procedures except inguinal and femoral w CC"  
label var drgid_477_averagepayment "Biopsies of musculoskeletal system and connective tissue w MCC"  
label var drgid_331_averagepayment "Major small and large bowel procedures w/o CC/MCC"  
label var drgid_657_averagepayment "Kidney and ureter procedures for neoplasm w CC"  
label var drgid_471_averagepayment "Cervical spinal fusion w MCC"  
label var drgid_417_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w MCC"  
label var drgid_225_averagepayment "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w/o MCC"  
label var drgid_414_averagepayment "Cholecystectomy except by laparoscope w/o c.d.e. w MCC"  
label var drgid_39_averagepayment "Extracranial procedures w/o CC/MCC"  
label var drgid_743_averagepayment "Uterine and adnexa proc for non-malignancy w/o CC/MCC"  
label var drgid_637_averagepayment "Diabetes w MCC"  
label var drgid_478_averagepayment "Biopsies of musculoskeletal system and connective tissue w CC"  
label var drgid_280_averagepayment "Acute myocardial infarction, discharged alive w MCC"  
label var drgid_658_averagepayment "Kidney and ureter procedures for neoplasm w/o CC/MCC"  
label var drgid_466_averagepayment "Revision of hip or knee replacement w MCC"  
label var drgid_472_averagepayment "Cervical spinal fusion w CC"  
label var drgid_226_averagepayment "Cardiac defibrillator implant w/o cardiac cath w MCC"  
label var drgid_675_averagepayment "Other kidney and urinary tract procedures w/o CC/MCC"  
label var drgid_237_averagepayment "Major cardiovasc procedures w MCC or thoracic aortic aneurysm repair"  
label var drgid_329_averagepayment "Major small and large bowel procedures w MCC"  
label var comp_hip_knee_higherestimate "Rate of complications for hip/knee replacement patients"  
label var iqi_11_aaa_higherestimate ""  
label var iqi_19_hip_fx_higherestimate ""  
label var iqi_91_conds_higherestimate ""  
label var mort_30_ami_higherestimate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_cabg_higherestimate "Death rate for CABG"  
label var mort_30_copd_higherestimate "Death rate for chronic obstructive pulmonary disease (COPD) patients"  
label var mort_30_hf_higherestimate "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_higherestimate "Pneumonia (PN) 30-Day Mortality Rate"  
label var mort_30_stk_higherestimate "Death rate for stroke patients"  
label var psi_11_postop_respfail_higherest ""  
label var psi_12_postop_pulmemb_dvt_higher "Serious blood clots after surgery"  
label var psi_13_post_sepsis_higherestimat "Blood stream infection after surgery"  
label var psi_14_postop_dehis_higherestima "A wound that splits open  after surgery on the abdomen or pelvis"  
label var psi_15_acc_lac_higherestimate "Accidental cuts and tears from medical treatment"  
label var psi_3_ulcer_higherestimate "Pressure sores"  
label var psi_4_surg_comp_higherestimate "Deaths among Patients with Serious Treatable Complications after Surgery"  
label var psi_6_iat_ptx_higherestimate "Collapsed lung due to medical treatment"  
label var psi_7_cvcbi_higherestimate "Infections from a large venous catheter"  
label var psi_8_post_hip_higherestimate "Broken hip from a fall after surgery"  
label var psi_90_safety_higherestimate "Serious complications"  
label var readm_30_ami_higherestimate "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_cabg_higherestimate "Rate of readmission for CABG"  
label var readm_30_copd_higherestimate "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_higherestimate "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_higherestimate "Rate of readmission after hip/knee replacement"  
label var readm_30_hosp_wide_higherestimat "Rate of readmission after discharge from hospital (hospital-wide)"  
label var readm_30_pn_higherestimate "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_stk_higherestimate "Rate of readmission for stroke patients"  
label var drgid_419_denominator "Laparoscopic cholecystectomy w/o c.d.e. w/o CC/MCC"  
label var drgid_227_denominator "Cardiac defibrillator implant w/o cardiac cath w/o MCC"  
label var drgid_459_denominator "Spinal fusion except cervical w MCC"  
label var drgid_674_denominator "Other kidney and urinary tract procedures w CC"  
label var drgid_508_denominator "Major shoulder or elbow joint procedures w/o CC/MCC"  
label var drgid_247_denominator "Perc cardiovasc proc w drug-eluting stent w/o MCC"  
label var drgid_282_denominator "Acute myocardial infarction, discharged alive w/o CC/MCC"  
label var drgid_219_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w MCC"  
label var drgid_328_denominator "Stomach, esophageal duodenal proc w/o CC/MCC"  
label var drgid_460_denominator "Spinal fusion except cervical w/o MCC"  
label var drgid_291_denominator "Heart failure and shock w MCC"  
label var drgid_491_denominator "Back and neck proc exc spinal fusion w/o CC/MCC"  
label var drgid_191_denominator "Chronic obstructive pulmonary disease w CC"  
label var drgid_354_denominator "Hernia procedures except inguinal and femoral w CC"  
label var drgid_477_denominator "Biopsies of musculoskeletal system and connective tissue w MCC"  
label var drgid_331_denominator "Major small and large bowel procedures w/o CC/MCC"  
label var drgid_657_denominator "Kidney and ureter procedures for neoplasm w CC"  
label var drgid_471_denominator "Cervical spinal fusion w MCC"  
label var drgid_417_denominator "Laparoscopic cholecystectomy w/o c.d.e. w MCC"  
label var drgid_225_denominator "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w/o MCC"  
label var drgid_414_denominator "Cholecystectomy except by laparoscope w/o c.d.e. w MCC"  
label var drgid_39_denominator "Extracranial procedures w/o CC/MCC"  
label var drgid_743_denominator "Uterine and adnexa proc for non-malignancy w/o CC/MCC"  
label var drgid_637_denominator "Diabetes w MCC"  
label var drgid_478_denominator "Biopsies of musculoskeletal system and connective tissue w CC"  
label var drgid_280_denominator "Acute myocardial infarction, discharged alive w MCC"  
label var drgid_658_denominator "Kidney and ureter procedures for neoplasm w/o CC/MCC"  
label var drgid_466_denominator "Revision of hip or knee replacement w MCC"  
label var drgid_472_denominator "Cervical spinal fusion w CC"  
label var drgid_226_denominator "Cardiac defibrillator implant w/o cardiac cath w MCC"  
label var drgid_675_denominator "Other kidney and urinary tract procedures w/o CC/MCC"  
label var drgid_237_denominator "Major cardiovasc procedures w MCC or thoracic aortic aneurysm repair"  
label var drgid_329_denominator "Major small and large bowel procedures w MCC"  
label var drgid_220_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w CC"  
label var drgid_469_denominator "Major joint replacement or reattachment of lower extremity w MCC"  
label var drgid_515_denominator "Other musculoskelet sys and conn tiss O.R. proc w MCC"  
label var drgid_243_denominator "Permanent cardiac pacemaker implant w CC"  
label var ctid_3_pnid_4_avgspendstate "Home Health Agency"  
label var ctid_6_pnid_2_avgspendstate "Outpatient"  
label var ctid_5_pnid_1_avgspendstate "Inpatient"  
label var ctid_4_pnid_2_avgspendstate "Hospice"  
label var ctid_3_pnid_1_avgspendstate "Home Health Agency"  
label var ctid_3_pnid_2_avgspendstate "Home Health Agency"  
label var ctid_1_pnid_2_avgspendstate "Carrier"  
label var ctid_7_pnid_4_avgspendstate "Skilled Nursing Facility"  
label var ctid_5_pnid_4_avgspendstate "Inpatient"  
label var ctid_7_pnid_1_avgspendstate "Skilled Nursing Facility"  
label var ctid_2_pnid_1_avgspendstate "Durable Medical Equipment"  
label var ctid_8_pnid_3_avgspendstate "Total"  
label var ctid_4_pnid_4_avgspendstate "Hospice"  
label var ctid_2_pnid_4_avgspendstate "Durable Medical Equipment"  
label var ctid_5_pnid_2_avgspendstate "Inpatient"  
label var ctid_4_pnid_1_avgspendstate "Hospice"  
label var ctid_6_pnid_4_avgspendstate "Outpatient"  
label var ctid_1_pnid_4_avgspendstate "Carrier"  
label var ctid_7_pnid_2_avgspendstate "Skilled Nursing Facility"  
label var ctid_6_pnid_1_avgspendstate "Outpatient"  
label var ctid_2_pnid_2_avgspendstate "Durable Medical Equipment"  
label var ctid_1_pnid_1_avgspendstate "Carrier"  
label var comp_hip_knee_denominator "Rate of complications for hip/knee replacement patients"  
label var iqi_11_aaa_denominator ""  
label var iqi_19_hip_fx_denominator ""  
label var iqi_91_conds_denominator ""  
label var mort_30_ami_denominator "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_cabg_denominator "Death rate for CABG"  
label var mort_30_copd_denominator "Death rate for chronic obstructive pulmonary disease (COPD) patients"  
label var mort_30_hf_denominator "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_denominator "Pneumonia (PN) 30-Day Mortality Rate"  
label var mort_30_stk_denominator "Death rate for stroke patients"  
label var psi_11_postop_respfail_denominat ""  
label var psi_12_postop_pulmemb_dvt_denomi "Serious blood clots after surgery"  
label var psi_13_post_sepsis_denominator "Blood stream infection after surgery"  
label var psi_14_postop_dehis_denominator "A wound that splits open  after surgery on the abdomen or pelvis"  
label var psi_15_acc_lac_denominator "Accidental cuts and tears from medical treatment"  
label var psi_3_ulcer_denominator "Pressure sores"  
label var psi_4_surg_comp_denominator "Deaths among Patients with Serious Treatable Complications after Surgery"  
label var psi_6_iat_ptx_denominator "Collapsed lung due to medical treatment"  
label var psi_7_cvcbi_denominator "Infections from a large venous catheter"  
label var psi_8_post_hip_denominator "Broken hip from a fall after surgery"  
label var psi_90_safety_denominator "Serious complications"  
label var readm_30_ami_denominator "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_cabg_denominator "Rate of readmission for CABG"  
label var readm_30_copd_denominator "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_denominator "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_denominator "Rate of readmission after hip/knee replacement"  
label var readm_30_hosp_wide_denominator "Rate of readmission after discharge from hospital (hospital-wide)"  
label var readm_30_pn_denominator "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_stk_denominator "Rate of readmission for stroke patients"  
label var comp_hip_knee_nationalcomparison "Rate of complications for hip/knee replacement patients"  
label var iqi_11_aaa_nationalcomparisoncat ""  
label var iqi_19_hip_fx_nationalcomparison ""  
label var iqi_91_conds_nationalcomparisonc ""  
label var mort_30_ami_nationalcomparisonca "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"  
label var mort_30_cabg_nationalcomparisonc "Death rate for CABG"  
label var mort_30_copd_nationalcomparisonc "Death rate for chronic obstructive pulmonary disease (COPD) patients"  
label var mort_30_hf_nationalcomparisoncat "Heart failure (HF) 30-Day Mortality Rate"  
label var mort_30_pn_nationalcomparisoncat "Pneumonia (PN) 30-Day Mortality Rate"  
label var mort_30_stk_nationalcomparisonca "Death rate for stroke patients"  
label var psi_11_postop_respfail_nationalc ""  
label var psi_12_postop_pulmemb_dvt_nation "Serious blood clots after surgery"  
label var psi_13_post_sepsis_nationalcompa "Blood stream infection after surgery"  
label var psi_14_postop_dehis_nationalcomp "A wound that splits open  after surgery on the abdomen or pelvis"  
label var psi_15_acc_lac_nationalcompariso "Accidental cuts and tears from medical treatment"  
label var psi_3_ulcer_nationalcomparisonca "Pressure sores"  
label var psi_4_surg_comp_nationalcomparis "Deaths among Patients with Serious Treatable Complications after Surgery"  
label var psi_6_iat_ptx_nationalcomparison "Collapsed lung due to medical treatment"  
label var psi_7_cvcbi_nationalcomparisonca "Infections from a large venous catheter"  
label var psi_8_post_hip_nationalcompariso "Broken hip from a fall after surgery"  
label var psi_90_safety_nationalcomparison "Serious complications"  
label var readm_30_ami_nationalcomparisonc "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"  
label var readm_30_cabg_nationalcomparison "Rate of readmission for CABG"  
label var readm_30_copd_nationalcomparison "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"  
label var readm_30_hf_nationalcomparisonca "Heart failure (HF) 30-Day Readmission Rate"  
label var readm_30_hip_knee_nationalcompar "Rate of readmission after hip/knee replacement"  
label var readm_30_hosp_wide_nationalcompa "Rate of readmission after discharge from hospital (hospital-wide)"  
label var readm_30_pn_nationalcomparisonca "Pneumonia (PN) 30-Day Readmission Rate"  
label var readm_30_stk_nationalcomparisonc "Rate of readmission for stroke patients"  
label var h_clean_hsp_a_p_answerpercent "Patients who reported that their room and bathroom were Always clean"  
label var h_clean_hsp_sn_p_answerpercent "Patients who reported that their room and bathroom were Sometimes or Never clean"  
label var h_clean_hsp_u_p_answerpercent "Patients who reported that their room and bathroom were Usually clean"  
label var h_clean_linear_score_answerperce "Cleanliness - linear mean score"  
label var h_clean_star_rating_answerpercen "Cleanliness - star rating"  
label var h_comp_1_a_p_answerpercent "Patients who reported that their nurses Always communicated well"  
label var h_comp_1_linear_score_answerperc "Nurse communication - linear mean score"  
label var h_comp_1_sn_p_answerpercent "Patients who reported that their nurses Sometimes or Never communicated well"  
label var h_comp_1_star_rating_answerperce "Nurse communication - star rating"  
label var h_comp_1_u_p_answerpercent "Patients who reported that their nurses Usually communicated well"  
label var h_comp_2_a_p_answerpercent "Patients who reported that their doctors Always communicated well"  
label var h_comp_2_linear_score_answerperc "Doctor communication - linear mean score"  
label var h_comp_2_sn_p_answerpercent "Patients who reported that their doctors Sometimes or Never communicated well"  
label var h_comp_2_star_rating_answerperce "Doctor communication - star rating"  
label var h_comp_2_u_p_answerpercent "Patients who reported that their doctors Usually communicated well"  
label var h_comp_3_a_p_answerpercent "Patients who reported that they Always received help as soon as they wanted"  
label var h_comp_3_linear_score_answerperc "Staff responsiveness - linear mean score"  
label var h_comp_3_sn_p_answerpercent "Patients who reported that they Sometimes or Never received help as soon as they"  
label var h_comp_3_star_rating_answerperce "Staff responsiveness - star rating"  
label var h_comp_3_u_p_answerpercent "Patients who reported that they Usually received help as soon as they wanted"  
label var h_comp_4_a_p_answerpercent "Patients who reported that their pain was Always well controlled"  
label var h_comp_4_linear_score_answerperc "Pain management - linear mean score"  
label var h_comp_4_sn_p_answerpercent "Patients who reported that their pain was Sometimes or Never well controlled"  
label var h_comp_4_star_rating_answerperce "Pain management - star rating"  
label var h_comp_4_u_p_answerpercent "Patients who reported that their pain was Usually well controlled"  
label var h_comp_5_a_p_answerpercent "Patients who reported that staff Always explained about medicines before giving "  
label var h_comp_5_linear_score_answerperc "Communication about medicines - linear mean score"  
label var h_comp_5_sn_p_answerpercent "Patients who reported that staff Sometimes or Never explained about medicines be"  
label var h_comp_5_star_rating_answerperce "Communication about medicines - star rating"  
label var h_comp_5_u_p_answerpercent "Patients who reported that staff Usually explained about medicines before giving"  
label var h_comp_6_linear_score_answerperc "Discharge information - linear mean score"  
label var h_comp_6_n_p_answerpercent "Patients who reported that NO, they were not given information about what to do "  
label var h_comp_6_star_rating_answerperce "Discharge information - star rating"  
label var h_comp_6_y_p_answerpercent "Patients who reported that YES, they were given information about what to do dur"  
label var h_comp_7_a_answerpercent "Patients who “Agree” they understood their care when they left the hospital"  
label var h_comp_7_d_sd_answerpercent "Patients who “Disagree” or “Strongly Disagree” they understood their care when t"  
label var h_comp_7_linear_score_answerperc "Care transition - linear mean score"  
label var h_comp_7_sa_answerpercent "Patients who Strongly Agree they understood their care when they left the hospit"  
label var h_comp_7_star_rating_answerperce "Care transition - star rating"  
label var h_hsp_rating_0_6_answerpercent "Patients who gave their hospital a rating of 6 or lower on a scale from 0 (lowes"  
label var h_hsp_rating_7_8_answerpercent "Patients who gave their hospital a rating of 7 or 8 on a scale from 0 (lowest) t"  
label var h_hsp_rating_9_10_answerpercent "Patients who gave their hospital a rating of 9 or 10 on a scale from 0 (lowest) "  
label var h_hsp_rating_linear_score_answer "Overall hospital rating - linear mean score"  
label var h_hsp_rating_star_rating_answerp "Overall hospital rating - star rating"  
label var h_quiet_hsp_a_p_answerpercent "Patients who reported that the area around their room was Always quiet at night"  
label var h_quiet_hsp_sn_p_answerpercent "Patients who reported that the area around their room was Sometimes or Never qui"  
label var h_quiet_hsp_u_p_answerpercent "Patients who reported that the area around their room was Usually quiet at night"  
label var h_quiet_linear_score_answerperce "Quietness - linear mean score"  
label var h_quiet_star_rating_answerpercen "Quietness - star rating"  
label var h_recmnd_dn_answerpercent "Patients who reported NO, they would probably not or definitely not recommend th"  
label var h_recmnd_dy_answerpercent "Patients who reported YES, they would definitely recommend the hospital"  
label var h_recmnd_linear_score_answerperc "Recommend hospital - linear mean score"  
label var h_recmnd_py_answerpercent "Patients who reported YES, they would probably recommend the hospital"  
label var h_recmnd_star_rating_answerperce "Recommend hospital - star rating"  
label var h_star_rating_answerpercent "Summary star rating"  
label var ctid_3_pnid_4_avgspendhosp "Home Health Agency"  
label var ctid_6_pnid_2_avgspendhosp "Outpatient"  
label var ctid_5_pnid_1_avgspendhosp "Inpatient"  
label var ctid_4_pnid_2_avgspendhosp "Hospice"  
label var ctid_3_pnid_1_avgspendhosp "Home Health Agency"  
label var ctid_3_pnid_2_avgspendhosp "Home Health Agency"  
label var ctid_1_pnid_2_avgspendhosp "Carrier"  
label var ctid_7_pnid_4_avgspendhosp "Skilled Nursing Facility"  
label var ctid_5_pnid_4_avgspendhosp "Inpatient"  
label var ctid_7_pnid_1_avgspendhosp "Skilled Nursing Facility"  
label var ctid_2_pnid_1_avgspendhosp "Durable Medical Equipment"  
label var ctid_8_pnid_3_avgspendhosp "Total"  
label var ctid_4_pnid_4_avgspendhosp "Hospice"  
label var ctid_2_pnid_4_avgspendhosp "Durable Medical Equipment"  
label var ctid_5_pnid_2_avgspendhosp "Inpatient"  
label var ctid_4_pnid_1_avgspendhosp "Hospice"  
label var ctid_6_pnid_4_avgspendhosp "Outpatient"  
label var ctid_1_pnid_4_avgspendhosp "Carrier"  
label var ctid_7_pnid_2_avgspendhosp "Skilled Nursing Facility"  
label var ctid_6_pnid_1_avgspendhosp "Outpatient"  
label var ctid_2_pnid_2_avgspendhosp "Durable Medical Equipment"  
label var ctid_1_pnid_1_avgspendhosp "Carrier"  