label var h_comp_7_linear_score_answerperc "Care transition - linear mean score"
label var h_comp_7_star_rating_answerperce "Care transition - star rating"
label var h_clean_linear_score_answerperce "Cleanliness - linear mean score"
label var h_clean_star_rating_answerpercen "Cleanliness - star rating"
label var h_comp_5_linear_score_answerperc "Communication about medicines - linear mean score"
label var h_comp_5_star_rating_answerperce "Communication about medicines - star rating"
label var h_comp_6_linear_score_answerperc "Discharge information - linear mean score"
label var h_comp_6_star_rating_answerperce "Discharge information - star rating"
label var h_comp_2_linear_score_answerperc "Doctor communication - linear mean score"
label var h_comp_2_star_rating_answerperce "Doctor communication - star rating"
label var h_comp_1_linear_score_answerperc "Nurse communication - linear mean score"
label var h_comp_1_star_rating_answerperce "Nurse communication - star rating"
label var h_hsp_rating_linear_score_answer "Overall hospital rating - linear mean score"
label var h_hsp_rating_star_rating_answerp "Overall hospital rating - star rating"
label var h_comp_4_linear_score_answerperc "Pain management - linear mean score"
label var h_comp_4_star_rating_answerperce "Pain management - star rating"
label var h_comp_7_a_answerpercent "Patients who “Agree” they understood their care when they left the hospital"
label var h_comp_7_d_sd_answerpercent "Patients who “Disagree” or “Strongly Disagree” they understood their care when t"
label var h_hsp_rating_0_6_answerpercent "Patients who gave their hospital a rating of 6 or lower on a scale from 0 (lowes"
label var h_hsp_rating_7_8_answerpercent "Patients who gave their hospital a rating of 7 or 8 on a scale from 0 (lowest) t"
label var h_hsp_rating_9_10_answerpercent "Patients who gave their hospital a rating of 9 or 10 on a scale from 0 (lowest) "
label var h_recmnd_dn_answerpercent "Patients who reported NO, they would probably not or definitely not recommend th"
label var h_comp_6_n_p_answerpercent "Patients who reported that NO, they were not given information about what to do "
label var h_comp_5_a_p_answerpercent "Patients who reported that staff Always explained about medicines before giving "
label var h_comp_5_sn_p_answerpercent "Patients who reported that staff Sometimes or Never explained about medicines be"
label var h_comp_5_u_p_answerpercent "Patients who reported that staff Usually explained about medicines before giving"
label var h_quiet_hsp_a_p_answerpercent "Patients who reported that the area around their room was Always quiet at night"
label var h_quiet_hsp_sn_p_answerpercent "Patients who reported that the area around their room was Sometimes or Never qui"
label var h_quiet_hsp_u_p_answerpercent "Patients who reported that the area around their room was Usually quiet at night"
label var h_comp_2_a_p_answerpercent "Patients who reported that their doctors Always communicated well"
label var h_comp_2_sn_p_answerpercent "Patients who reported that their doctors Sometimes or Never communicated well"
label var h_comp_2_u_p_answerpercent "Patients who reported that their doctors Usually communicated well"
label var h_comp_1_a_p_answerpercent "Patients who reported that their nurses Always communicated well"
label var h_comp_1_sn_p_answerpercent "Patients who reported that their nurses Sometimes or Never communicated well"
label var h_comp_1_u_p_answerpercent "Patients who reported that their nurses Usually communicated well"
label var h_comp_4_a_p_answerpercent "Patients who reported that their pain was Always well controlled"
label var h_comp_4_sn_p_answerpercent "Patients who reported that their pain was Sometimes or Never well controlled"
label var h_comp_4_u_p_answerpercent "Patients who reported that their pain was Usually well controlled"
label var h_clean_hsp_a_p_answerpercent "Patients who reported that their room and bathroom were Always clean"
label var h_clean_hsp_sn_p_answerpercent "Patients who reported that their room and bathroom were Sometimes or Never clean"
label var h_clean_hsp_u_p_answerpercent "Patients who reported that their room and bathroom were Usually clean"
label var h_comp_3_a_p_answerpercent "Patients who reported that they Always received help as soon as they wanted"
label var h_comp_3_sn_p_answerpercent "Patients who reported that they Sometimes or Never received help as soon as they"
label var h_comp_3_u_p_answerpercent "Patients who reported that they Usually received help as soon as they wanted"
label var h_comp_6_y_p_answerpercent "Patients who reported that YES, they were given information about what to do dur"
label var h_recmnd_dy_answerpercent "Patients who reported YES, they would definitely recommend the hospital"
label var h_recmnd_py_answerpercent "Patients who reported YES, they would probably recommend the hospital"
label var h_comp_7_sa_answerpercent "Patients who Strongly Agree they understood their care when they left the hospit"
label var h_quiet_linear_score_answerperce "Quietness - linear mean score"
label var h_quiet_star_rating_answerpercen "Quietness - star rating"
label var h_recmnd_linear_score_answerperc "Recommend hospital - linear mean score"
label var h_recmnd_star_rating_answerperce "Recommend hospital - star rating"
label var h_comp_3_linear_score_answerperc "Staff responsiveness - linear mean score"
label var h_comp_3_star_rating_answerperce "Staff responsiveness - star rating"
label var h_star_rating_answerpercent "Summary star rating"
