label var hai_1_confidenceintervalhigher "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_confidenceintervallower "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_nationalcomparisoncategory "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_numberofdaysorpatients "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_numerator "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_standardizedinfectionratio "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1a_confidenceintervalhigher "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_1a_confidenceintervallower "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_1a_nationalcomparisoncategor "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_1a_numberofdaysorpatients "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_1a_numerator "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_1a_standardizedinfectionrati "Central line-associated blood stream infections (CLABSI) in ICUs only"
label var hai_2_confidenceintervalhigher "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_confidenceintervallower "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_nationalcomparisoncategory "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_numberofdaysorpatients "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_numerator "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_standardizedinfectionratio "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2a_confidenceintervalhigher "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_2a_confidenceintervallower "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_2a_nationalcomparisoncategor "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_2a_numberofdaysorpatients "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_2a_numerator "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_2a_standardizedinfectionrati "Catheter-Associated Urinary Tract Infections (CAUTI) in ICUs only"
label var hai_3_confidenceintervalhigher "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_confidenceintervallower "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_nationalcomparisoncategory "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_numberofdaysorpatients "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_numerator "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_standardizedinfectionratio "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_4_confidenceintervalhigher "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_confidenceintervallower "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_nationalcomparisoncategory "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_numberofdaysorpatients "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_numerator "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_standardizedinfectionratio "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_5_confidenceintervalhigher "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_5_confidenceintervallower "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_5_nationalcomparisoncategory "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_5_numberofdaysorpatients "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_5_numerator "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_5_standardizedinfectionratio "Methicillin-resistant Staphylococcus Aureus (MRSA) Blood Laboratory-identified E"
label var hai_6_confidenceintervalhigher "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
label var hai_6_confidenceintervallower "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
label var hai_6_nationalcomparisoncategory "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
label var hai_6_numberofdaysorpatients "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
label var hai_6_numerator "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
label var hai_6_standardizedinfectionratio "Clostridium difficile (C.diff.) Laboratory-identified Events (Intestinal infecti"
