label var combinedssimeasurescore_achie ""
label var combinedssimeasurescore_impro ""
label var combinedssimeasurescore_measu ""
label var combinedssimeasurescore_perfo ""
label var hai_1_achievementpoints "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_improvementpoints "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_measurescore "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_1_performancerate "Central line-associated bloodstream infections (CLABSI) in ICUs and select wards"
label var hai_2_achievementpoints "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_improvementpoints "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_measurescore "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_2_performancerate "Catheter-associated urinary tract infections (CAUTI) in ICUs and select wards"
label var hai_3_achievementpoints "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_improvementpoints "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_measurescore "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_3_performancerate "Surgical Site Infection from colon surgery (SSI: Colon)"
label var hai_4_achievementpoints "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_improvementpoints "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_measurescore "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var hai_4_performancerate "Surgical Site Infection from abdominal hysterectomy (SSI: Hysterectomy)"
label var haiconditionprocedurescore_ac ""
label var haiconditionprocedurescore_im ""
label var haiconditionprocedurescore_me ""
label var haiconditionprocedurescore_pe ""
label var hf_1_achievementpoints "Discharge instructions"
label var hf_1_improvementpoints "Discharge instructions"
label var hf_1_measurescore "Discharge instructions"
label var hf_1_performancerate "Discharge instructions"
label var hfconditionprocedurescore_ach ""
label var hfconditionprocedurescore_imp ""
label var hfconditionprocedurescore_mea ""
label var hfconditionprocedurescore_per ""
label var imm_2_achievementpoints "Immunization for influenza"
label var imm_2_improvementpoints "Immunization for influenza"
label var imm_2_measurescore "Immunization for influenza"
label var imm_2_performancerate "Immunization for influenza"
label var mort_30_ami_achievementpoints "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_improvementpoints "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_measurescore "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_performancerate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_hf_achievementpoints "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_improvementpoints "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_measurescore "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_performancerate "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_pn_achievementpoints "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_improvementpoints "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_measurescore "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_performancerate "Pneumonia (PN) 30-Day Mortality Rate"
label var mspb_1_achievementpoints "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"
label var mspb_1_improvementpoints "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"
label var mspb_1_measurescore "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"
label var mspb_1_performancerate "Medicare spending per beneficiary (MSPB) or spending per patient (SPP)"
label var pn_3b_achievementpoints "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_3b_improvementpoints "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_3b_measurescore "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_3b_performancerate "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_6_achievementpoints "Initial antibiotic selection for CAP in immunocompetent patient"
label var pn_6_improvementpoints "Initial antibiotic selection for CAP in immunocompetent patient"
label var pn_6_measurescore "Initial antibiotic selection for CAP in immunocompetent patient"
label var pn_6_performancerate "Initial antibiotic selection for CAP in immunocompetent patient"
label var pnconditionprocedurescore_ach ""
label var pnconditionprocedurescore_imp ""
label var pnconditionprocedurescore_mea ""
label var pnconditionprocedurescore_per ""
label var preventiveconditionprocedures ""
label var psi_90_safety_achievementpoints "Serious complications"
label var psi_90_safety_improvementpoints "Serious complications"
label var psi_90_safety_measurescore "Serious complications"
label var psi_90_safety_performancerate "Serious complications"
label var scip_card_2_achievementpoints "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_card_2_improvementpoints "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_card_2_measurescore "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_card_2_performancerate "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_inf_1_achievementpoints "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_1_improvementpoints "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_1_measurescore "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_1_performancerate "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_2_achievementpoints "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_2_improvementpoints "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_2_measurescore "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_2_performancerate "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_3_achievementpoints "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_3_improvementpoints "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_3_measurescore "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_3_performancerate "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_4_achievementpoints "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_4_improvementpoints "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_4_measurescore "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_4_performancerate "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_9_achievementpoints "Postoperative Urinary Catheter Removal"
label var scip_inf_9_improvementpoints "Postoperative Urinary Catheter Removal"
label var scip_inf_9_measurescore "Postoperative Urinary Catheter Removal"
label var scip_inf_9_performancerate "Postoperative Urinary Catheter Removal"
label var scip_vte_1_achievementpoints "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_1_improvementpoints "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_1_measurescore "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_1_performancerate "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_2_achievementpoints "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var scip_vte_2_improvementpoints "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var scip_vte_2_measurescore "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var scip_vte_2_performancerate "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var scipconditionprocedurescore_a ""
label var scipconditionprocedurescore_i ""
label var scipconditionprocedurescore_m ""
label var scipconditionprocedurescore_p ""
