label var mid_1_achievementpoints "CLEANLINESS AND QUIETNESS OF HOSPITAL ENVIRONMENT"
label var mid_1_dimensionscore "CLEANLINESS AND QUIETNESS OF HOSPITAL ENVIRONMENT"
label var mid_2_achievementpoints "COMMUNICATION ABOUT MEDICINES"
label var mid_2_dimensionscore "COMMUNICATION ABOUT MEDICINES"
label var mid_3_achievementpoints "COMMUNICATION WITH DOCTORS"
label var mid_3_dimensionscore "COMMUNICATION WITH DOCTORS"
label var mid_4_achievementpoints "COMMUNICATION WITH NURSES"
label var mid_4_dimensionscore "COMMUNICATION WITH NURSES"
label var mid_5_achievementpoints "DISCHARGE INFORMATION"
label var mid_5_dimensionscore "DISCHARGE INFORMATION"
label var mid_6_achievementpoints "OVERALL RATING OF HOSPITAL"
label var mid_6_dimensionscore "OVERALL RATING OF HOSPITAL"
label var mid_7_achievementpoints "PAIN MANAGEMENT"
label var mid_7_dimensionscore "PAIN MANAGEMENT"
label var mid_8_achievementpoints "RESPONSIVENESS OF HOSPITAL STAFF"
label var mid_8_dimensionscore "RESPONSIVENESS OF HOSPITAL STAFF"
