label var drgid_190_averagepayment "Chronic obstructive pulmonary disease w MCC"
label var drgid_190_denominator "Chronic obstructive pulmonary disease w MCC"
label var drgid_191_averagepayment "Chronic obstructive pulmonary disease w CC"
label var drgid_191_denominator "Chronic obstructive pulmonary disease w CC"
label var drgid_192_averagepayment "Chronic obstructive pulmonary disease w/o CC/MCC"
label var drgid_192_denominator "Chronic obstructive pulmonary disease w/o CC/MCC"
label var drgid_193_averagepayment "Simple pneumonia and pleurisy w MCC"
label var drgid_193_denominator "Simple pneumonia and pleurisy w MCC"
label var drgid_219_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w MCC"
label var drgid_219_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w MCC"
label var drgid_220_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w CC"
label var drgid_220_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w CC"
label var drgid_221_averagepayment "Cardiac valve and oth maj cardiothoracic proc w/o card cath w/o CC/MCC"
label var drgid_221_denominator "Cardiac valve and oth maj cardiothoracic proc w/o card cath w/o CC/MCC"
label var drgid_224_averagepayment "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w MCC"
label var drgid_224_denominator "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w MCC"
label var drgid_225_averagepayment "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w/o MCC"
label var drgid_225_denominator "Cardiac defib implant w cardiac cath w/o AMI/HF/shock w/o MCC"
label var drgid_226_averagepayment "Cardiac defibrillator implant w/o cardiac cath w MCC"
label var drgid_226_denominator "Cardiac defibrillator implant w/o cardiac cath w MCC"
label var drgid_227_averagepayment "Cardiac defibrillator implant w/o cardiac cath w/o MCC"
label var drgid_227_denominator "Cardiac defibrillator implant w/o cardiac cath w/o MCC"
label var drgid_235_averagepayment "Coronary bypass w/o cardiac cath w MCC"
label var drgid_235_denominator "Coronary bypass w/o cardiac cath w MCC"
label var drgid_236_averagepayment "Coronary bypass w/o cardiac cath w/o MCC"
label var drgid_236_denominator "Coronary bypass w/o cardiac cath w/o MCC"
label var drgid_237_averagepayment "Major cardiovasc procedures w MCC or thoracic aortic aneurysm repair"
label var drgid_237_denominator "Major cardiovasc procedures w MCC or thoracic aortic aneurysm repair"
label var drgid_243_averagepayment "Permanent cardiac pacemaker implant w CC"
label var drgid_243_denominator "Permanent cardiac pacemaker implant w CC"
label var drgid_244_averagepayment "Permanent cardiac pacemaker implant w/o CC/MCC"
label var drgid_244_denominator "Permanent cardiac pacemaker implant w/o CC/MCC"
label var drgid_247_averagepayment "Perc cardiovasc proc w drug-eluting stent w/o MCC"
label var drgid_247_denominator "Perc cardiovasc proc w drug-eluting stent w/o MCC"
label var drgid_280_averagepayment "Acute myocardial infarction, discharged alive w MCC"
label var drgid_280_denominator "Acute myocardial infarction, discharged alive w MCC"
label var drgid_281_averagepayment "Acute myocardial infarction, discharged alive w CC"
label var drgid_281_denominator "Acute myocardial infarction, discharged alive w CC"
label var drgid_282_averagepayment "Acute myocardial infarction, discharged alive w/o CC/MCC"
label var drgid_282_denominator "Acute myocardial infarction, discharged alive w/o CC/MCC"
label var drgid_291_averagepayment "Heart failure and shock w MCC"
label var drgid_291_denominator "Heart failure and shock w MCC"
label var drgid_292_averagepayment "Heart failure and shock w CC"
label var drgid_292_denominator "Heart failure and shock w CC"
label var drgid_293_averagepayment "Heart failure and shock w/o CC/MCC"
label var drgid_293_denominator "Heart failure and shock w/o CC/MCC"
label var drgid_313_averagepayment "Chest Pain"
label var drgid_313_denominator "Chest Pain"
label var drgid_328_averagepayment "Stomach, esophageal duodenal proc w/o CC/MCC"
label var drgid_328_denominator "Stomach, esophageal duodenal proc w/o CC/MCC"
label var drgid_329_averagepayment "Major small and large bowel procedures w MCC"
label var drgid_329_denominator "Major small and large bowel procedures w MCC"
label var drgid_330_averagepayment "Major small and large bowel procedures w CC"
label var drgid_330_denominator "Major small and large bowel procedures w CC"
label var drgid_331_averagepayment "Major small and large bowel procedures w/o CC/MCC"
label var drgid_331_denominator "Major small and large bowel procedures w/o CC/MCC"
label var drgid_353_averagepayment "Hernia procedures except inguinal and femoral w MCC"
label var drgid_353_denominator "Hernia procedures except inguinal and femoral w MCC"
label var drgid_354_averagepayment "Hernia procedures except inguinal and femoral w CC"
label var drgid_354_denominator "Hernia procedures except inguinal and femoral w CC"
label var drgid_355_averagepayment "Hernia procedures except inguinal and femoral w/o CC/MCC"
label var drgid_355_denominator "Hernia procedures except inguinal and femoral w/o CC/MCC"
label var drgid_38_averagepayment "Extracranial procedures w CC"
label var drgid_38_denominator "Extracranial procedures w CC"
label var drgid_39_averagepayment "Extracranial procedures w/o CC/MCC"
label var drgid_39_denominator "Extracranial procedures w/o CC/MCC"
label var drgid_414_averagepayment "Cholecystectomy except by laparoscope w/o c.d.e. w MCC"
label var drgid_414_denominator "Cholecystectomy except by laparoscope w/o c.d.e. w MCC"
label var drgid_417_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w MCC"
label var drgid_417_denominator "Laparoscopic cholecystectomy w/o c.d.e. w MCC"
label var drgid_418_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w CC"
label var drgid_418_denominator "Laparoscopic cholecystectomy w/o c.d.e. w CC"
label var drgid_419_averagepayment "Laparoscopic cholecystectomy w/o c.d.e. w/o CC/MCC"
label var drgid_419_denominator "Laparoscopic cholecystectomy w/o c.d.e. w/o CC/MCC"
label var drgid_459_averagepayment "Spinal fusion except cervical w MCC"
label var drgid_459_denominator "Spinal fusion except cervical w MCC"
label var drgid_460_averagepayment "Spinal fusion except cervical w/o MCC"
label var drgid_460_denominator "Spinal fusion except cervical w/o MCC"
label var drgid_461_averagepayment "Bilateral or multiple major joint procs of lower extremity w MCC"
label var drgid_461_denominator "Bilateral or multiple major joint procs of lower extremity w MCC"
label var drgid_462_averagepayment "Bilateral or multiple major joint procs of lower extremity w/o MCC"
label var drgid_462_denominator "Bilateral or multiple major joint procs of lower extremity w/o MCC"
label var drgid_466_averagepayment "Revision of hip or knee replacement w MCC"
label var drgid_466_denominator "Revision of hip or knee replacement w MCC"
label var drgid_467_averagepayment "Revision of hip or knee replacement w CC"
label var drgid_467_denominator "Revision of hip or knee replacement w CC"
label var drgid_468_averagepayment "Revision of hip or knee replacement w/o CC/MCC"
label var drgid_468_denominator "Revision of hip or knee replacement w/o CC/MCC"
label var drgid_469_averagepayment "Major joint replacement or reattachment of lower extremity w MCC"
label var drgid_469_denominator "Major joint replacement or reattachment of lower extremity w MCC"
label var drgid_470_averagepayment "Major joint replacement or reattachment of lower extremity w/o MCC"
label var drgid_470_denominator "Major joint replacement or reattachment of lower extremity w/o MCC"
label var drgid_471_averagepayment "Cervical spinal fusion w MCC"
label var drgid_471_denominator "Cervical spinal fusion w MCC"
label var drgid_472_averagepayment "Cervical spinal fusion w CC"
label var drgid_472_denominator "Cervical spinal fusion w CC"
label var drgid_473_averagepayment "Cervical spinal fusion w/o CC/MCC"
label var drgid_473_denominator "Cervical spinal fusion w/o CC/MCC"
label var drgid_477_averagepayment "Biopsies of musculoskeletal system and connective tissue w MCC"
label var drgid_477_denominator "Biopsies of musculoskeletal system and connective tissue w MCC"
label var drgid_478_averagepayment "Biopsies of musculoskeletal system and connective tissue w CC"
label var drgid_478_denominator "Biopsies of musculoskeletal system and connective tissue w CC"
label var drgid_479_averagepayment "Biopsies of musculoskeletal system and connective tissue w/o CC/MCC"
label var drgid_479_denominator "Biopsies of musculoskeletal system and connective tissue w/o CC/MCC"
label var drgid_490_averagepayment "Back and neck proc exc spinal fusion w CC/MCC or disc device/neurostim"
label var drgid_490_denominator "Back and neck proc exc spinal fusion w CC/MCC or disc device/neurostim"
label var drgid_491_averagepayment "Back and neck proc exc spinal fusion w/o CC/MCC"
label var drgid_491_denominator "Back and neck proc exc spinal fusion w/o CC/MCC"
label var drgid_507_averagepayment "Major shoulder or elbow joint procedures w CC/MCC"
label var drgid_507_denominator "Major shoulder or elbow joint procedures w CC/MCC"
label var drgid_508_averagepayment "Major shoulder or elbow joint procedures w/o CC/MCC"
label var drgid_508_denominator "Major shoulder or elbow joint procedures w/o CC/MCC"
label var drgid_515_averagepayment "Other musculoskelet sys and conn tiss O.R. proc w MCC"
label var drgid_515_denominator "Other musculoskelet sys and conn tiss O.R. proc w MCC"
label var drgid_637_averagepayment "Diabetes w MCC"
label var drgid_637_denominator "Diabetes w MCC"
label var drgid_656_averagepayment "Kidney and ureter procedures for neoplasm w MCC"
label var drgid_656_denominator "Kidney and ureter procedures for neoplasm w MCC"
label var drgid_657_averagepayment "Kidney and ureter procedures for neoplasm w CC"
label var drgid_657_denominator "Kidney and ureter procedures for neoplasm w CC"
label var drgid_658_averagepayment "Kidney and ureter procedures for neoplasm w/o CC/MCC"
label var drgid_658_denominator "Kidney and ureter procedures for neoplasm w/o CC/MCC"
label var drgid_659_averagepayment "Kidney and ureter procedures for non-neoplasm w MCC"
label var drgid_659_denominator "Kidney and ureter procedures for non-neoplasm w MCC"
label var drgid_668_averagepayment "Transurethral procedures w MCC"
label var drgid_668_denominator "Transurethral procedures w MCC"
label var drgid_673_averagepayment "Other kidney and urinary tract procedures w MCC"
label var drgid_673_denominator "Other kidney and urinary tract procedures w MCC"
label var drgid_674_averagepayment "Other kidney and urinary tract procedures w CC"
label var drgid_674_denominator "Other kidney and urinary tract procedures w CC"
label var drgid_675_averagepayment "Other kidney and urinary tract procedures w/o CC/MCC"
label var drgid_675_denominator "Other kidney and urinary tract procedures w/o CC/MCC"
label var drgid_713_averagepayment "Transurethral prostatectomy w CC/MCC"
label var drgid_713_denominator "Transurethral prostatectomy w CC/MCC"
label var drgid_714_averagepayment "Transurethral prostatectomy w/o CC/MCC"
label var drgid_714_denominator "Transurethral prostatectomy w/o CC/MCC"
label var drgid_743_averagepayment "Uterine and adnexa proc for non-malignancy w/o CC/MCC"
label var drgid_743_denominator "Uterine and adnexa proc for non-malignancy w/o CC/MCC"
label var drgid_748_averagepayment "Female reproductive system reconstructive procedures"
label var drgid_748_denominator "Female reproductive system reconstructive procedures"
