label var op_10_sample "Abdomen CT Use of Contrast Material"
label var op_10_score "Abdomen CT Use of Contrast Material"
label var op_11_sample "Thorax CT Use of Contrast Material"
label var op_11_score "Thorax CT Use of Contrast Material"
label var op_13_sample "Outpatients who got cardiac imaging stress tests before low-risk outpatient surg"
label var op_13_score "Outpatients who got cardiac imaging stress tests before low-risk outpatient surg"
label var op_14_sample "Outpatients with brain CT scans who got a sinus CT scan at the same time"
label var op_14_score "Outpatients with brain CT scans who got a sinus CT scan at the same time"
label var op_8_sample "MRI Lumbar Spine for Low Back Pain"
label var op_8_score "MRI Lumbar Spine for Low Back Pain"
label var op_9_sample "Mammography Follow-up Rates"
label var op_9_score "Mammography Follow-up Rates"
