label var ctid_1_pnid_1_avgspendhosp "Carrier"
label var ctid_1_pnid_1_avgspendstate "Carrier"
label var ctid_1_pnid_2_avgspendhosp "Carrier"
label var ctid_1_pnid_2_avgspendstate "Carrier"
label var ctid_1_pnid_4_avgspendhosp "Carrier"
label var ctid_1_pnid_4_avgspendstate "Carrier"
label var ctid_2_pnid_1_avgspendhosp "Durable Medical Equipment"
label var ctid_2_pnid_1_avgspendstate "Durable Medical Equipment"
label var ctid_2_pnid_2_avgspendhosp "Durable Medical Equipment"
label var ctid_2_pnid_2_avgspendstate "Durable Medical Equipment"
label var ctid_2_pnid_4_avgspendhosp "Durable Medical Equipment"
label var ctid_2_pnid_4_avgspendstate "Durable Medical Equipment"
label var ctid_3_pnid_1_avgspendhosp "Home Health Agency"
label var ctid_3_pnid_1_avgspendstate "Home Health Agency"
label var ctid_3_pnid_2_avgspendhosp "Home Health Agency"
label var ctid_3_pnid_2_avgspendstate "Home Health Agency"
label var ctid_3_pnid_4_avgspendhosp "Home Health Agency"
label var ctid_3_pnid_4_avgspendstate "Home Health Agency"
label var ctid_4_pnid_1_avgspendhosp "Hospice"
label var ctid_4_pnid_1_avgspendstate "Hospice"
label var ctid_4_pnid_2_avgspendhosp "Hospice"
label var ctid_4_pnid_2_avgspendstate "Hospice"
label var ctid_4_pnid_4_avgspendhosp "Hospice"
label var ctid_4_pnid_4_avgspendstate "Hospice"
label var ctid_5_pnid_1_avgspendhosp "Inpatient"
label var ctid_5_pnid_1_avgspendstate "Inpatient"
label var ctid_5_pnid_2_avgspendhosp "Inpatient"
label var ctid_5_pnid_2_avgspendstate "Inpatient"
label var ctid_5_pnid_4_avgspendhosp "Inpatient"
label var ctid_5_pnid_4_avgspendstate "Inpatient"
label var ctid_6_pnid_1_avgspendhosp "Outpatient"
label var ctid_6_pnid_1_avgspendstate "Outpatient"
label var ctid_6_pnid_2_avgspendhosp "Outpatient"
label var ctid_6_pnid_2_avgspendstate "Outpatient"
label var ctid_6_pnid_4_avgspendhosp "Outpatient"
label var ctid_6_pnid_4_avgspendstate "Outpatient"
label var ctid_7_pnid_1_avgspendhosp "Skilled Nursing Facility"
label var ctid_7_pnid_1_avgspendstate "Skilled Nursing Facility"
label var ctid_7_pnid_2_avgspendhosp "Skilled Nursing Facility"
label var ctid_7_pnid_2_avgspendstate "Skilled Nursing Facility"
label var ctid_7_pnid_4_avgspendhosp "Skilled Nursing Facility"
label var ctid_7_pnid_4_avgspendstate "Skilled Nursing Facility"
label var ctid_8_pnid_3_avgspendhosp "Total"
label var ctid_8_pnid_3_avgspendstate "Total"
