label var mid_60_ptid_7_procedurevolume "OTHER"
label var mid_60_ptid_1_procedurevolume "CARDIOVASCULAR"
label var mid_60_ptid_4_procedurevolume "GENITOURINARY"
label var mid_60_ptid_2_procedurevolume "EYE"
label var mid_60_ptid_5_procedurevolume "MUSCULOSKELETAL"
label var mid_60_ptid_8_procedurevolume "RESPIRATORY"
label var mid_60_ptid_9_procedurevolume "SKIN"
label var mid_60_ptid_3_procedurevolume "GASTROINTESTINAL"
label var mid_60_ptid_6_procedurevolume "NERVOUS SYSTEM"
