label var paym_30_ami_denominator "Payment for heart attack patients"
label var paym_30_ami_higherestimate "Payment for heart attack patients"
label var paym_30_ami_lowerestimate "Payment for heart attack patients"
label var paym_30_ami_nationalcomparisonca "Payment for heart attack patients"
label var paym_30_ami_payment "Payment for heart attack patients"
label var paym_30_hf_denominator "Payment for heart failure patients"
label var paym_30_hf_higherestimate "Payment for heart failure patients"
label var paym_30_hf_lowerestimate "Payment for heart failure patients"
label var paym_30_hf_nationalcomparisoncat "Payment for heart failure patients"
label var paym_30_hf_payment "Payment for heart failure patients"
label var paym_30_pn_denominator "Payment for pneumonia patients"
label var paym_30_pn_higherestimate "Payment for pneumonia patients"
label var paym_30_pn_lowerestimate "Payment for pneumonia patients"
label var paym_30_pn_nationalcomparisoncat "Payment for pneumonia patients"
label var paym_30_pn_payment "Payment for pneumonia patients"
