label var comp_hip_knee_denominator "Rate of complications for hip/knee replacement patients"
label var comp_hip_knee_higherestimate "Rate of complications for hip/knee replacement patients"
label var comp_hip_knee_lowerestimate "Rate of complications for hip/knee replacement patients"
label var comp_hip_knee_nationalcomparison "Rate of complications for hip/knee replacement patients"
label var comp_hip_knee_score "Rate of complications for hip/knee replacement patients"
label var iqi_11_aaa_denominator ""
label var iqi_11_aaa_higherestimate ""
label var iqi_11_aaa_lowerestimate ""
label var iqi_11_aaa_nationalcomparisoncat ""
label var iqi_11_aaa_score ""
label var iqi_19_hip_fx_denominator ""
label var iqi_19_hip_fx_higherestimate ""
label var iqi_19_hip_fx_lowerestimate ""
label var iqi_19_hip_fx_nationalcomparison ""
label var iqi_19_hip_fx_score ""
label var iqi_91_conds_denominator ""
label var iqi_91_conds_higherestimate ""
label var iqi_91_conds_lowerestimate ""
label var iqi_91_conds_nationalcomparisonc ""
label var iqi_91_conds_score ""
label var mort_30_ami_denominator "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_higherestimate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_lowerestimate "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_nationalcomparisonca "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_ami_score "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate"
label var mort_30_cabg_denominator "Death rate for CABG"
label var mort_30_cabg_higherestimate "Death rate for CABG"
label var mort_30_cabg_lowerestimate "Death rate for CABG"
label var mort_30_cabg_nationalcomparisonc "Death rate for CABG"
label var mort_30_cabg_score "Death rate for CABG"
label var mort_30_copd_denominator "Death rate for chronic obstructive pulmonary disease (COPD) patients"
label var mort_30_copd_higherestimate "Death rate for chronic obstructive pulmonary disease (COPD) patients"
label var mort_30_copd_lowerestimate "Death rate for chronic obstructive pulmonary disease (COPD) patients"
label var mort_30_copd_nationalcomparisonc "Death rate for chronic obstructive pulmonary disease (COPD) patients"
label var mort_30_copd_score "Death rate for chronic obstructive pulmonary disease (COPD) patients"
label var mort_30_hf_denominator "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_higherestimate "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_lowerestimate "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_nationalcomparisoncat "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_hf_score "Heart failure (HF) 30-Day Mortality Rate"
label var mort_30_pn_denominator "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_higherestimate "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_lowerestimate "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_nationalcomparisoncat "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_pn_score "Pneumonia (PN) 30-Day Mortality Rate"
label var mort_30_stk_denominator "Death rate for stroke patients"
label var mort_30_stk_higherestimate "Death rate for stroke patients"
label var mort_30_stk_lowerestimate "Death rate for stroke patients"
label var mort_30_stk_nationalcomparisonca "Death rate for stroke patients"
label var mort_30_stk_score "Death rate for stroke patients"
label var psi_11_postop_respfail_denominat ""
label var psi_11_postop_respfail_higherest ""
label var psi_11_postop_respfail_loweresti ""
label var psi_11_postop_respfail_nationalc ""
label var psi_11_postop_respfail_score ""
label var psi_12_postop_pulmemb_dvt_denomi "Serious blood clots after surgery"
label var psi_12_postop_pulmemb_dvt_higher "Serious blood clots after surgery"
label var psi_12_postop_pulmemb_dvt_lowere "Serious blood clots after surgery"
label var psi_12_postop_pulmemb_dvt_nation "Serious blood clots after surgery"
label var psi_12_postop_pulmemb_dvt_score "Serious blood clots after surgery"
label var psi_13_post_sepsis_denominator "Blood stream infection after surgery"
label var psi_13_post_sepsis_higherestimat "Blood stream infection after surgery"
label var psi_13_post_sepsis_lowerestimate "Blood stream infection after surgery"
label var psi_13_post_sepsis_nationalcompa "Blood stream infection after surgery"
label var psi_13_post_sepsis_score "Blood stream infection after surgery"
label var psi_14_postop_dehis_denominator "A wound that splits open  after surgery on the abdomen or pelvis"
label var psi_14_postop_dehis_higherestima "A wound that splits open  after surgery on the abdomen or pelvis"
label var psi_14_postop_dehis_lowerestimat "A wound that splits open  after surgery on the abdomen or pelvis"
label var psi_14_postop_dehis_nationalcomp "A wound that splits open  after surgery on the abdomen or pelvis"
label var psi_14_postop_dehis_score "A wound that splits open  after surgery on the abdomen or pelvis"
label var psi_15_acc_lac_denominator "Accidental cuts and tears from medical treatment"
label var psi_15_acc_lac_higherestimate "Accidental cuts and tears from medical treatment"
label var psi_15_acc_lac_lowerestimate "Accidental cuts and tears from medical treatment"
label var psi_15_acc_lac_nationalcompariso "Accidental cuts and tears from medical treatment"
label var psi_15_acc_lac_score "Accidental cuts and tears from medical treatment"
label var psi_3_ulcer_denominator "Pressure sores"
label var psi_3_ulcer_higherestimate "Pressure sores"
label var psi_3_ulcer_lowerestimate "Pressure sores"
label var psi_3_ulcer_nationalcomparisonca "Pressure sores"
label var psi_3_ulcer_score "Pressure sores"
label var psi_4_surg_comp_denominator "Deaths among Patients with Serious Treatable Complications after Surgery"
label var psi_4_surg_comp_higherestimate "Deaths among Patients with Serious Treatable Complications after Surgery"
label var psi_4_surg_comp_lowerestimate "Deaths among Patients with Serious Treatable Complications after Surgery"
label var psi_4_surg_comp_nationalcomparis "Deaths among Patients with Serious Treatable Complications after Surgery"
label var psi_4_surg_comp_score "Deaths among Patients with Serious Treatable Complications after Surgery"
label var psi_6_iat_ptx_denominator "Collapsed lung due to medical treatment"
label var psi_6_iat_ptx_higherestimate "Collapsed lung due to medical treatment"
label var psi_6_iat_ptx_lowerestimate "Collapsed lung due to medical treatment"
label var psi_6_iat_ptx_nationalcomparison "Collapsed lung due to medical treatment"
label var psi_6_iat_ptx_score "Collapsed lung due to medical treatment"
label var psi_7_cvcbi_denominator "Infections from a large venous catheter"
label var psi_7_cvcbi_higherestimate "Infections from a large venous catheter"
label var psi_7_cvcbi_lowerestimate "Infections from a large venous catheter"
label var psi_7_cvcbi_nationalcomparisonca "Infections from a large venous catheter"
label var psi_7_cvcbi_score "Infections from a large venous catheter"
label var psi_8_post_hip_denominator "Broken hip from a fall after surgery"
label var psi_8_post_hip_higherestimate "Broken hip from a fall after surgery"
label var psi_8_post_hip_lowerestimate "Broken hip from a fall after surgery"
label var psi_8_post_hip_nationalcompariso "Broken hip from a fall after surgery"
label var psi_8_post_hip_score "Broken hip from a fall after surgery"
label var psi_90_safety_denominator "Serious complications"
label var psi_90_safety_higherestimate "Serious complications"
label var psi_90_safety_lowerestimate "Serious complications"
label var psi_90_safety_nationalcomparison "Serious complications"
label var psi_90_safety_score "Serious complications"
label var readm_30_ami_denominator "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"
label var readm_30_ami_higherestimate "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"
label var readm_30_ami_lowerestimate "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"
label var readm_30_ami_nationalcomparisonc "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"
label var readm_30_ami_score "Acute Myocardial Infarction (AMI) 30-Day Readmission Rate"
label var readm_30_cabg_denominator "Rate of readmission for CABG"
label var readm_30_cabg_higherestimate "Rate of readmission for CABG"
label var readm_30_cabg_lowerestimate "Rate of readmission for CABG"
label var readm_30_cabg_nationalcomparison "Rate of readmission for CABG"
label var readm_30_cabg_score "Rate of readmission for CABG"
label var readm_30_copd_denominator "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"
label var readm_30_copd_higherestimate "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"
label var readm_30_copd_lowerestimate "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"
label var readm_30_copd_nationalcomparison "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"
label var readm_30_copd_score "Rate of readmission for chronic obstructive pulmonary disease (COPD) patients"
label var readm_30_hf_denominator "Heart failure (HF) 30-Day Readmission Rate"
label var readm_30_hf_higherestimate "Heart failure (HF) 30-Day Readmission Rate"
label var readm_30_hf_lowerestimate "Heart failure (HF) 30-Day Readmission Rate"
label var readm_30_hf_nationalcomparisonca "Heart failure (HF) 30-Day Readmission Rate"
label var readm_30_hf_score "Heart failure (HF) 30-Day Readmission Rate"
label var readm_30_hip_knee_denominator "Rate of readmission after hip/knee replacement"
label var readm_30_hip_knee_higherestimate "Rate of readmission after hip/knee replacement"
label var readm_30_hip_knee_lowerestimate "Rate of readmission after hip/knee replacement"
label var readm_30_hip_knee_nationalcompar "Rate of readmission after hip/knee replacement"
label var readm_30_hip_knee_score "Rate of readmission after hip/knee replacement"
label var readm_30_hosp_wide_denominator "Rate of readmission after discharge from hospital (hospital-wide)"
label var readm_30_hosp_wide_higherestimat "Rate of readmission after discharge from hospital (hospital-wide)"
label var readm_30_hosp_wide_lowerestimate "Rate of readmission after discharge from hospital (hospital-wide)"
label var readm_30_hosp_wide_nationalcompa "Rate of readmission after discharge from hospital (hospital-wide)"
label var readm_30_hosp_wide_score "Rate of readmission after discharge from hospital (hospital-wide)"
label var readm_30_pn_denominator "Pneumonia (PN) 30-Day Readmission Rate"
label var readm_30_pn_higherestimate "Pneumonia (PN) 30-Day Readmission Rate"
label var readm_30_pn_lowerestimate "Pneumonia (PN) 30-Day Readmission Rate"
label var readm_30_pn_nationalcomparisonca "Pneumonia (PN) 30-Day Readmission Rate"
label var readm_30_pn_score "Pneumonia (PN) 30-Day Readmission Rate"
label var readm_30_stk_denominator "Rate of readmission for stroke patients"
label var readm_30_stk_higherestimate "Rate of readmission for stroke patients"
label var readm_30_stk_lowerestimate "Rate of readmission for stroke patients"
label var readm_30_stk_nationalcomparisonc "Rate of readmission for stroke patients"
label var readm_30_stk_score "Rate of readmission for stroke patients"
