label var ami_1_sample "Heart Attack Patients Given Aspirin at Arrival"
label var ami_1_score "Heart Attack Patients Given Aspirin at Arrival"
label var ami_10_sample "Statin at Discharge"
label var ami_10_score "Statin at Discharge"
label var ami_2_sample "Aspirin prescribed at discharge"
label var ami_2_score "Aspirin prescribed at discharge"
label var ami_3_sample "Heart Attack Patients Given ACE Inhibitor or ARB for Left Ventricular Systolic D"
label var ami_3_score "Heart Attack Patients Given ACE Inhibitor or ARB for Left Ventricular Systolic D"
label var ami_4_sample "Heart Attack Patients Given Smoking Cessation Advice/Counseling"
label var ami_4_score "Heart Attack Patients Given Smoking Cessation Advice/Counseling"
label var ami_5_sample "Heart Attack Patients Given Beta Blocker at Discharge"
label var ami_5_score "Heart Attack Patients Given Beta Blocker at Discharge"
label var ami_7a_sample "Fibrinolytic Therapy Received Within 30 Minutes Of Hospital Arrival"
label var ami_7a_score "Fibrinolytic Therapy Received Within 30 Minutes Of Hospital Arrival"
label var ami_8a_sample "Primary PCI Received Within 90 Minutes of Hospital Arrival"
label var ami_8a_score "Primary PCI Received Within 90 Minutes of Hospital Arrival"
label var cac_1_sample "Relievers for Inpatient Asthma"
label var cac_1_score "Relievers for Inpatient Asthma"
label var cac_2_sample "Systemic Corticosteroids for Inpatient Asthma"
label var cac_2_score "Systemic Corticosteroids for Inpatient Asthma"
label var cac_3_sample "Home Management Plan of Care Document"
label var cac_3_score "Home Management Plan of Care Document"
label var ed_1b_sample "ED1"
label var ed_1b_score "ED1"
label var ed_2b_sample "ED2"
label var ed_2b_score "ED2"
label var edv_sample "Emergency department volume"
label var edv_score "Emergency department volume"
label var hf_1_sample "Discharge instructions"
label var hf_1_score "Discharge instructions"
label var hf_2_sample "Evaluation of LVS Function"
label var hf_2_score "Evaluation of LVS Function"
label var hf_3_sample "ACEI or ARB for LVSD"
label var hf_3_score "ACEI or ARB for LVSD"
label var hf_4_sample "Heart Failure Patients Given Smoking Cessation Advice/Counseling"
label var hf_4_score "Heart Failure Patients Given Smoking Cessation Advice/Counseling"
label var imm_1a_sample ""
label var imm_1a_score ""
label var imm_2_sample "Immunization for influenza"
label var imm_2_score "Immunization for influenza"
label var imm_3_fac_adhpct_sample "Healthcare workers given influenza vaccination"
label var imm_3_fac_adhpct_score "Healthcare workers given influenza vaccination"
label var imm_3_op_27_fac_adhpct_sample "Healthcare workers given influenza vaccination"
label var imm_3_op_27_fac_adhpct_score "Healthcare workers given influenza vaccination"
label var op_1_sample "Median Time to Fibrinolysis"
label var op_1_score "Median Time to Fibrinolysis"
label var op_18b_sample "OP 18"
label var op_18b_score "OP 18"
label var op_2_sample "Fibrinolytic Therapy Received Within 30 Minutes of ED Arrival"
label var op_2_score "Fibrinolytic Therapy Received Within 30 Minutes of ED Arrival"
label var op_20_sample "Door to diagnostic eval"
label var op_20_score "Door to diagnostic eval"
label var op_21_sample "Median time to pain med"
label var op_21_score "Median time to pain med"
label var op_22_sample "Left before being seen"
label var op_22_score "Left before being seen"
label var op_23_sample "Head CT results"
label var op_23_score "Head CT results"
label var op_29_sample "Endoscopy/Polyp Surveillance: Appropriate Follow-Up Interval for Normal Colonosc"
label var op_29_score "Endoscopy/Polyp Surveillance: Appropriate Follow-Up Interval for Normal Colonosc"
label var op_30_sample "Endoscopy/Polyp Surveillance: Colonoscopy Interval for Patients with a History o"
label var op_30_score "Endoscopy/Polyp Surveillance: Colonoscopy Interval for Patients with a History o"
label var op_3b_sample "Median Time to Transfer to Another Facility for Acute Coronary Intervention"
label var op_3b_score "Median Time to Transfer to Another Facility for Acute Coronary Intervention"
label var op_4_sample "Aspirin at Arrival"
label var op_4_score "Aspirin at Arrival"
label var op_5_sample "Median Time to ECG"
label var op_5_score "Median Time to ECG"
label var op_6_sample "Prophylactic Antibiotic Initiated Within One Hour Prior to Surgical Incision"
label var op_6_score "Prophylactic Antibiotic Initiated Within One Hour Prior to Surgical Incision"
label var op_7_sample "Prophylactic Antibiotic Selection for Surgical Patients"
label var op_7_score "Prophylactic Antibiotic Selection for Surgical Patients"
label var pc_01_sample "Percent of newborns whose deliveries were scheduled early (1-3 weeks early), whe"
label var pc_01_score "Percent of newborns whose deliveries were scheduled early (1-3 weeks early), whe"
label var pn_1_sample "Pneumonia Patients Given Oxygenation Assessment"
label var pn_1_score "Pneumonia Patients Given Oxygenation Assessment"
label var pn_2_sample "Pneumonia Patients Assessed and Given Pneumococcal Vaccination"
label var pn_2_score "Pneumonia Patients Assessed and Given Pneumococcal Vaccination"
label var pn_3b_sample "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_3b_score "Pneumonia Patients Whose Initial Emergency Room Blood Culture Was Performed Prio"
label var pn_4_sample "Pneumonia Patients Given Smoking Cessation Advice/Counseling"
label var pn_4_score "Pneumonia Patients Given Smoking Cessation Advice/Counseling"
label var pn_5c_sample "Pneumonia Patients Given Initial Antibiotic(s) within 6 Hours After Arrival"
label var pn_5c_score "Pneumonia Patients Given Initial Antibiotic(s) within 6 Hours After Arrival"
label var pn_6_sample "Initial antibiotic selection for CAP in immunocompetent patient"
label var pn_6_score "Initial antibiotic selection for CAP in immunocompetent patient"
label var pn_7_sample "Pneumonia Patients Assessed and Given Influenza Vaccination"
label var pn_7_score "Pneumonia Patients Assessed and Given Influenza Vaccination"
label var scip_card_2_sample "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_card_2_score "Surgery Patients on a Beta Blocker Prior to Arrival Who Received a Beta Blocker "
label var scip_inf_1_sample "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_1_score "Prophylactic antibiotic received within 1 hour prior to surgical incision"
label var scip_inf_10_sample "Surgery Patients with Perioperative Temperature Management"
label var scip_inf_10_score "Surgery Patients with Perioperative Temperature Management"
label var scip_inf_2_sample "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_2_score "Prophylactic Antibiotic Selection for Surgical Patients"
label var scip_inf_3_sample "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_3_score "Prophylactic antibiotics discontinued within 24 hours after surgery end time"
label var scip_inf_4_sample "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_4_score "Cardiac surgery patients with controlled 6 a.m. postoperative blood glucose"
label var scip_inf_6_sample "Surgery patients needing hair removed from the surgical area before surgery, who"
label var scip_inf_6_score "Surgery patients needing hair removed from the surgical area before surgery, who"
label var scip_inf_9_sample "Postoperative Urinary Catheter Removal"
label var scip_inf_9_score "Postoperative Urinary Catheter Removal"
label var scip_vte_1_sample "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_1_score "Surgery patients whose doctors ordered treatments to prevent blood clots after c"
label var scip_vte_2_sample "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var scip_vte_2_score "Surgery Patients Who Received Appropriate Venous Thromboembolism Prophylaxis Wit"
label var stk_1_sample "Venous Thromboembolism (VTE) Prophylaxis"
label var stk_1_score "Venous Thromboembolism (VTE) Prophylaxis"
label var stk_10_sample "Assessed for Rehabilitation"
label var stk_10_score "Assessed for Rehabilitation"
label var stk_2_sample "Discharged on Antithrombotic Therapy"
label var stk_2_score "Discharged on Antithrombotic Therapy"
label var stk_3_sample "Anticoagulation Therapy for Atrial Fibrillation/Flutter"
label var stk_3_score "Anticoagulation Therapy for Atrial Fibrillation/Flutter"
label var stk_4_sample "Thrombolytic Therapy"
label var stk_4_score "Thrombolytic Therapy"
label var stk_5_sample "Antithrombotic Therapy by End of Hospital Day 2"
label var stk_5_score "Antithrombotic Therapy by End of Hospital Day 2"
label var stk_6_sample "Discharged on Statin Medication"
label var stk_6_score "Discharged on Statin Medication"
label var stk_8_sample "Stroke Education"
label var stk_8_score "Stroke Education"
label var vte_1_sample "Venous thromboembolism prophylaxis"
label var vte_1_score "Venous thromboembolism prophylaxis"
label var vte_2_sample "ICU venous thromboembolism prophylaxis"
label var vte_2_score "ICU venous thromboembolism prophylaxis"
label var vte_3_sample "Anticoagulation overlap therapy"
label var vte_3_score "Anticoagulation overlap therapy"
label var vte_4_sample "Unfractionated heparin with dosages/platelet count monitoring"
label var vte_4_score "Unfractionated heparin with dosages/platelet count monitoring"
label var vte_5_sample "Warfarin therapy discharge instructions"
label var vte_5_score "Warfarin therapy discharge instructions"
label var vte_6_sample "Hospital acquired potentially preventable venous thromboembolism"
label var vte_6_score "Hospital acquired potentially preventable venous thromboembolism"
