label var tpsid_9_measurescore "Weighted Patient Experience of Care Domain Score"
label var tpsid_3_measurescore "Unweighted Normalized Efficiency Domain Score"
label var tpsid_6_measurescore "Weighted Clinical Process of Care Domain Score"
label var tpsid_7_measurescore "Weighted Efficiency Domain Score"
label var tpsid_1_measurescore "Total Performance Score"
label var tpsid_4_measurescore "Unweighted Normalized Outcome Domain Score"
label var tpsid_5_measurescore "Unweighted Patient Experience of Care Domain Score"
label var tpsid_2_measurescore "Unweighted Normalized Clinical Process of Care Domain Score"
label var tpsid_8_measurescore "Weighted Outcome Domain Score"
